### ISSUE TITLE
Compilation failure under rustc 1.0.0-beta.2

### ISSUE THREAD

**Issue by ldcasillas-progreso** [BurntSushi/xsv#10]
This could be me doing something wrong...

```
$ cargo build --release
   Compiling byteorder v0.3.7
   Compiling threadpool v0.1.4
   Compiling streaming-stats v0.1.23
   Compiling regex v0.1.28
   Compiling rustc-serialize v0.3.12
   Compiling libc v0.1.6
   Compiling log v0.3.1
/Users/luis.casillas/.cargo/registry/src/github.com-1ecc6299db9ec823/streaming-stats-0.1.23/src/lib.rs:1:1: 1:41 error: unstable feature
/Users/luis.casillas/.cargo/registry/src/github.com-1ecc6299db9ec823/streaming-stats-0.1.23/src/lib.rs:1 #![feature(collections, core, std_misc)]
                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `streaming-stats`.

$ git log | head -n 5
commit c19cf0bf43d001ee0555d943eb6703c058152877
Author: Andrew Gallant <jamslam@gmail.com>
Date:   Thu Apr 16 17:50:25 2015 -0400

    crates.io merit badge
```

**Comment by ldcasillas-progreso** [comment]
I did a `cargo update` and that didn't help.

**Comment by BurntSushi** [comment]
`xsv` does not compile on beta (and some of its dependencies don't either). I'm not sure when it will work, but to use `xsv` you unfortunately need to use Rust nightlies.

**Comment by ldcasillas-progreso** [comment]
Right.  I got confused because the Rust homepage gives 1.0.0-beta2 as the recommended version.  Thanks!

**Comment by BurntSushi** [comment]
Yup, no worries. beta is definitely recommended. I should put a note in the README. There are a few things that didn't get stabilized in time for Rust 1.0 that `xsv` needs. Hopefully `xsv` will compile on Rust 1.1 (which will be out 6 weeks after 1.0).

**Comment by ldcasillas-progreso** [comment]
Well, I just tried compiling 0.9.5 under 1.1 and that doesn't work either.  I think you really ought to put a note in the README's installation section of what Rust version is required.

**Comment by BurntSushi** [comment]
Ah! I thought it would build fine on `1.1.0`, but I actually had one small issue left to fix. `0.9.6` should build on Rust 1.1.0 now. Sorry for the inconvenience!

**Comment by ldcasillas-progreso** [comment]
Yup, it compiles now.  Thanks!
