### ISSUE TITLE
feature request: max field width in `xsv table`

### ISSUE THREAD

**Issue by nhoffman** [BurntSushi/xsv#101]
I frequently run into csv files with one or more "large" fields - this presents an obvious problem for any tool meant for viewing the file in a terminal (as acknowledged by the disclaimer in the help text for `xsv table`: "This will not work well if the CSV data contains large fields."). Any chance of adding an argument like `-W/--max-width` that would truncate fields to N characters? 

I'd even perhaps attempt to make the case that the default behavior should be to truncate fields at some reasonable default with the option to override - this seems better aligned with the purpose of conveniently viewing the contents of a csv file. But simply adding an option to limit field width would obviously be the more conservative approach.

Thanks a lot for this utility!

**Comment by BurntSushi** [comment]
Both the `xsv flatten` and `xsv table` commands have a `-c/--condense` flag that I feel satisfies this use case. What do you think?

**Comment by nhoffman** [comment]
It absolutely does! Thanks for your response, and apologies for not reading (the perfectly clear) docstring. I guess "condense" must have subconsciously suggested something else.
