### ISSUE TITLE
XSV Removing Rows?

### ISSUE THREAD

**Issue by nikhiljha** [BurntSushi/xsv#103]
PS > xsv index train.csv
PS > xsv index oil.csv
PS > xsv join date oil.csv date train.csv -o oiltrain.csv

$ wc -l oiltrain.csv
87710369 oiltrain.csv
$ wc -l train.csv
125497041 train.csv

train has a bunch of columns with dates and some other data
oil has two columns, date and oil

When combining, I expected it to add an oil column for every date - which is what it looks like it did in the example with the country abbreviations.

Is this expected behavior? Did I misunderstand?

**Comment by BurntSushi** [comment]
@nikhiljha Thanks for the report! Please provide enough information for others to reproduce your problem. Please also show the output you get *and* the output you expected to get. So, that's three things:

1. Please provide input data.
2. Please provide actual output.
3. Please provide expected output.

**Comment by nikhiljha** [comment]
I wasn't doing a full outer join, which is what I wanted. Full outer join seems to work.
