### ISSUE TITLE
TSV

### ISSUE THREAD

**Issue by alienzj** [BurntSushi/xsv#104]
Hello!
Can this great tool work on tsv files?
Thanks very much!

**Comment by BurntSushi** [comment]
Yes. You might consider looking at the `--help` of an `xsv` command. You'd see:

```
    -d, --delimiter <arg>  The field delimiter for reading CSV data.
                           Must be a single character. (default: ,)
```

Alternatively, if the file has an extension `.tsv`, then a tab delimiter is used automatically.

**Comment by ManavalanG** [comment]
Has this feature been deprecated? It is not available for me in `v0.13.0`.

**Comment by BurntSushi** [comment]
@ManavalanG No, it hasn't been deprecated. Please file a bug report with **detailed reproducible instructions** on what's not working as expected. Saying "it doesn't work" or "isn't available" is not sufficient. Please include the command you're running, the input, the actual output and the expected output.

**Comment by erlangparasu** [comment]
Any Updates?
`xsv --help` not shwing docs about delimiter option in version v0.13.0
