### ISSUE TITLE
Can't parse some text

### ISSUE THREAD

**Issue by dufferzafar** [BurntSushi/xsv#105]
xsv is unable to parse these lines:

(when run `xsv input --quote '"' --escape "\\" -- /tmp/err.csv`)

```csv
1,"a",2,"b","free form text","d","3",3339,1,"4",\N
1,"a",2,"b","\"A Freelance Webdeveloper, Me.\"",\N,"3",\N,1,"4",\N
```

The csv was generated by MySQL, and can be parsed by the Python's csv module:

```python
data = csv.reader(open("/tmp/err.csv"), quotechar='"', escapechar="\\")
```

**Comment by BurntSushi** [comment]
Thanks for the report! This is fixed on master. Silly mistake on my part!
