### ISSUE TITLE
Export to SQL - discussion on possible new "sqlexport" command

### ISSUE THREAD

**Issue by oschonrock** [BurntSushi/xsv#111]
Thanks for an exellent rust-csv crate and xsv bin! Awesome performance!

This not an "issue" per se, but a prompt for discussion. Is that OK here, or is there a better place?

**Motivation**: We regularly get given a folder full of CSVs to parse, restructure and then import into an application database. We usually do this by creating a temp SQL DB importing the CSVs into that, doing the cleanup / restructure, eg adding PKs, FKs, querying and joining tables, perhaps creating views for convenient browsing / querying. Then re-export a subset of the tables/columns as CSV in a standardised form and import into our application using its standard "ETL". Or use SQL or a client script to update the app-db from the temp db. 

Tools for parsing and getting the CSVs into the temp db are remarkably limited. The "best" we have found is csvsql from the python csvkit. It works OK, but is very slow. eg for 58 CSVs (most of data in 10 of them) total size 11MB, csvsql took 72mins to parse, create db and insert. The bottleneck was clearly the python process maxed out at 100% CPU (on one core of course) with db server CPU and disk I/O almost idle. 

I am an experienced programmer in various languages but a novice to Rust. I found your rust csv-crate and was going to implement a command line tool in Rust with a subset of the py-csvsql functionality using the rust-csv crate, to try to learn some more Rust. Then I found xsv, which actually does quite a lot of what would be required, particularly the xsv stats command, does all the parsing to figure out what field types would be appropriate in SQL. So I am enquiring whether there is interest in integrating "Export to SQL" like functionality similar to csvsql directly into xsv, or whether this should be a separate project. 

If this of interest here are some thoughts:

1. Given the performance of xsv I suspect the DB / I/O will quickly become the bottleneck. So not sure if printing the "CREATE TABLE....INSERT INTO..." SQL to stdout is best. This would be piped to relevant db client compressed/saved for later inserting. Would this be most conformant to the unix philosophy of "each program, does one thing". Or should xsv access the DB directly the way csvsql does? I think there will be architectural, usability and concurrency tradeoffs here...
2. There is often a pre-processing step of converting the CSVs (which are usually from some horrendous legacy system) to utf8 (they are often in ISO8859 or CP1252). We use iconv command line with a simple shell loop and this works fine and is reasonably fast (a few seconds for above 11MB, 58 CSV dataset). Is this worth integrating, or should it remain a separate step?
3. Once the data is in the temp DB we usually add an auto_increment PKs to everything straight away, because SQL tools don't work well without one.  Then we try to identify a real PK in the actual CSV data, by trial adding unique indeces and ultimately promote one of those to become the real PK for that table. Then we try to indentify FKs using field name heuristics and left joins, and add them removing any rows which are "broken FKs" (most CSV sets have those). We also often apply some field naming conventions to the whole DB (lowercase "_" delim etc). How much of this "post processing/restructuring" should go into xsv? Or this better done as a separate process and perhaps written in a less performant, lighter-touch scripting language, given performance is now all down to the DB anyway?
4. Which SQL dialects are important? We use MySql.  Postgresql would be the other obvious candidate. 
5. What's a suitable dev process? Fork this repo, restructure some of the "stats" command fns so its functionality can be reused, and add an additional command, eg "sqlexport" to do the above. Then create PR?

Feedback wanted!

Thanks

**Comment by BurntSushi** [comment]
Hi! Thanks for the write up. I think someone might have asked about this
before. Basically, I strongly feel like this should be a separate project.
The primary reason is that I don't personally have the bandwidth to
maintain something like this, but in general, I also feel like this type of
task isn't really in scope. It strikes me as a very domain dependent thing.

Your point about the stats command is acknowledged though. I will say that
I am not too happy with it and it could be improved quite a bit (probably
rewritten). I would be potentially interested in factoring this code into a
separate crate that these tools could share though!

**Comment by oschonrock** [comment]
I agree that 2 & 3 above feel "domain specific" and should probably be separate. The remaining task would be 

1. generate "CREATE TABLE...INSERT..." SQL for the parsed CSV and (to keep it simple) print that sql to stdout. Keep it to one dialect (MySQL/MariaDB) but implemented so that other contributors can add adapters. 

Do you feel this is a separate project too? If we can agree, and I can get this off the ground, I could write and maintain that "module/command". 

Alternatively, I could "borrow" some of your XSV code to start a separate project. If it turns out that there is enough code in the stats command which could live in shared crate that could happen. But I suspect there is not enough there, having had a cursory look at the code. 

It is perhaps more likely that the generating "CREATE TABLE..." SQL in the relevant dialects  from some vendor neutral DB structure notation could be a separate crate (maybe exists?).

**Comment by BurntSushi** [comment]
Honestly, I don't know. I definitely think it is domain specific because of the different SQL syntax. I would rather it be a separate project.

**Comment by oschonrock** [comment]
Fair enough. 
I agree the dialects are annoying. If I get the time, I will see what I can cobble together, borrowing some of your stuff, and using the csv-crate obviously. If it turns out to be easy and looks like it might be worth reviewing this discussion, I will come back to you. 
You can close this if you want.

**Comment by BurntSushi** [comment]
Thanks! Sounds like it could be a great tool. :-)
