### ISSUE TITLE
Enable magic for .tab file extension

### ISSUE THREAD

**Issue by tseemann** [BurntSushi/xsv#115]
I noticed in a comment that `.tsv` files get some defaults changed automatically.

Can you enable this for `.tab` files too, a common alternative TSV extension?

Or honour a `XSV_TSV_EXTENSIONS=tab,tsv` env var?

Much like the much desired `XSV_DEFAULT_DELIMITER` etc

**Comment by BurntSushi** [comment]
I don't think I've ever heard of the `tab` extension, but the [Wikipedia article does list it along with `tsv`](https://en.wikipedia.org/wiki/Tab-separated_values). A PR would be welcome.
