### ISSUE TITLE
Command documentation and running tests for binary install?

### ISSUE THREAD

**Issue by rickhg12hs** [BurntSushi/xsv#118]
After `cargo install xsv`, the executable is in `~/.cargo/bin` as expected.
Is there command documentation?... Something like a man page?
Is it possible to run the package tests on the installed binary?

**Comment by BurntSushi** [comment]
> Is there command documentation?... Something like a man page?

No. There's a README and `xsv --help`. I don't have the bandwidth to maintain a man page for this project at this time.

> Is it possible to run the package tests on the installed binary?

No, sorry, although you could probably do it with a bit of hacking. If you want to run the tests, then checkout the repo and run `cargo test`.
