### ISSUE TITLE
Is there a Changelog for 13.0 release?

### ISSUE THREAD

**Issue by tseemann** [BurntSushi/xsv#120]
Thank you for the latest 13.0 release.  There was no information on the Release page about what was changed. I looked for a Changelog file or similar, without luck.  Is there one?

**Comment by BurntSushi** [comment]
Nope. I don't maintain a CHANGELOG for every project because it is too much work. xsv don't get a lot of traffic, so I think reading the commit messages is a decent substitute.

**Comment by tseemann** [comment]
I understand the lack of time, but I disagree with it being a decent substitute. The author is the person best placed to skim over all the commit messages since the last release and summarise the key ones in  the textbox for the Github release, especially for a major release (12 -> 13).
