### ISSUE TITLE
xsv sample: option to specify seed?

### ISSUE THREAD

**Issue by dannguyen** [BurntSushi/xsv#124]
As [I commented in another issue](https://github.com/BurntSushi/xsv/issues/119), `xsv sample`'s performance feels pretty good to me, and I'd like to use it as part of a project in which I'm putting together data transformation pipelines, including creating a sample CSV (for demo and distribution purposes) from a much larger CSV.

In general, the actual records in the raw data are deterministic, and I'd like to have a deterministic sample if possible. Ideally I just produce the sample once, but in reality, I usually fumble up my script and re-run steps over and over. It'd be great if I could provide a seed for whatever `xsv` uses to do random sampling, e.g.

```sh
$ xsv sample --seed 42 100000 data.csv
```

I understand that my use case is very niche, so obviously consider this low priority :)

**Comment by BurntSushi** [comment]
This seems reasonable to me. I don't know when or if I'll do this myself, but PRs are welcome!
