### ISSUE TITLE
Building fails on macos

### ISSUE THREAD

**Issue by simschla** [BurntSushi/xsv#13]
`cargo build --release` yields the following error on mac os

~~~~
/Users/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/filetime-0.1.2/src/lib.rs:83:29: 83:57 error: unresolved import `std::os::macos::fs::MetadataExt`. Could not find `macos` in `std::os`
/Users/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/filetime-0.1.2/src/lib.rs:83                         use std::os::$i::fs::MetadataExt;
~~~~

Cannot build on macos because of this issue. Any tips/hints would be greatly appreciated

**Comment by BurntSushi** [comment]
This is actually a problem in the dependency, `filetime`, which was reported here: https://github.com/alexcrichton/filetime/issues/1

`xsv` does indeed require the Rust nightly compiler, but hopefully not for long. Can you share version info? Try running:

```bash
rustc --version
cargo --version
```

Thanks!

**Comment by simschla** [comment]
Sure thing. I'm currently using rust 1.0.0 stable

~~~~
$ rustc --version
rustc 1.0.0 (built 2015-05-16)

$ cargo --version
cargo 0.2.0 (a483581 2015-05-14) (built 2015-05-16)
~~~~

**Comment by BurntSushi** [comment]
Yeah, `xsv` doesn't work on stable yet. Sorry. Hopefully soon.

If you want to give it a whirl now, you'll need to grab the nightly compiler.
