### ISSUE TITLE
Please support the SSV flavour of CSV

### ISSUE THREAD

**Issue by mirabilos** [BurntSushi/xsv#133]
Hi,

first, for reference, my full SSV toolkit is [here](https://evolvis.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=shellsnippets/shellsnippets.git;a=tree;f=mksh/ssv;hb=HEAD).

SSV (“separator-separated value”, yes, the name is… suboptimal, but it’s what we have) is a CSV variant that can very easily and reliably be read and written from shell scripts (POSIX too, but I prefer Korn). It’s basically:

- ASCII Field Separator `\x1C` is the field separator (not tab, semicolon or comma)
- ASCII newline `\x0A` is record separator (like in most Unix CSV), never CR+LF
- embedded newlines in fields are encoded with `\x0D` (CR)
- there is neither a quoting character nor an escaping character
- ⇒ which means that `\x1C` is disallowed in field content (no big loss), and newlines in field content are normalised to one ending (`\x0D ` only internally, can be LF or CR+LF on the outside when converting from/to CSV)

The canonical CSV to SSV converter `csv2ssv.c` from the above-linked git repo
- aborts when encountering a NUL (`\x00`) or FS (`\x1C`) byte (but one could just strip them out)
- has configurable “in-bound” field separator and quote characters
- handles LF or CR+LF newlines on the input (CSV) side, converting to just LF for line end and just CR for inside a field
- expects a newline at end of file, and no unclosed quotes
- … but that’s just a suggestion

The canonical SSV to CSV converter is just this shell script:

    sed \
        -e 's/"/""/g' \
        -e 's/^/"/' \
        -e 's/$/"/' \
        -e $'s/\x1C/"\t"/g'

It
- doubles every double quote (content) first
- puts a double quote at the begin and end of each line
- replaces the field separator by (ending) double quote, tab, (beginning) double quote
- effectively creates a tab-separated file, keeping embedded newlines as CR only

LibreOffice and Softmaker Office both handle these files correctly.

**Comment by BurntSushi** [comment]
Can you explain what `xsv` is missing to support this today? `xsv input` should expose what you need.

If the format is designed to be parseable by standard shell tools, then the benefits of xsv are not nearly as pronounced. The point of xsv is that it handles CSV correctly.

**Comment by mirabilos** [comment]
Andrew Gallant dixit:

>Can you explain what `xsv` is missing to support this today?

Support for SSV as *output* format, perhaps?

**Comment by BurntSushi** [comment]
Again, please describe what's missing from `xsv` to make this happen today. See `xsv fmt`.

**Comment by mirabilos** [comment]
Andrew Gallant dixit:

>Again, please describe what's missing from `xsv` to make this happen today. See `xsv fmt`.

I don’t know, I can’t run xsv because it’s not packaged in
Debian and it’s not written in one of the dozen-and-a-half-
or-so programming languages I know, but a coworker gave me
a comma-separated CSV file produced by this tool, and I’d
prefer an SSV-formatted CSV file instead.

**Comment by BurntSushi** [comment]
Then ask your co-worker to figure out how to generate an SSV formatted file with `xsv`, and if they can't, they can file a feature request explaining exactly what's missing. Otherwise, as far as I know, this is already possible.

FYI: there are binary releases you can download and run on any Linux distro: https://github.com/BurntSushi/xsv/releases
