### ISSUE TITLE
Confusing errors for invalid and incorrectly-cased subcommand

### ISSUE THREAD

**Issue by huonw** [BurntSushi/xsv#138]
```
$ cat example.csv
name,age,height
John Smith,10,1.2
Jane Smith,11,1.3
```

If an subcommand is missing or mistyped, then there's an error message that lists out the possible subcommands in title case:

```
$ xsv staats example.csv 
Could not match 'staats' with any of the allowed variants: ["Cat", "Count", "FixLengths", "Flatten", "Fmt", "Frequency", "Headers", "Help", "Index", "Input", "Join", "Partition", "Sample", "Search", "Select", "Slice", "Sort", "Split", "Stats", "Table"]
```

However, following that guidance and using title case too gives another error message that doesn't explicitly specify what the mistake was (it should be lowercase):

```
$ xsv Stats example.csv 
Invalid arguments.

Usage:
    xsv stats [options] [<input>]
```

**Comment by ad-si** [comment]
@BurntSushi Can you maybe release a new version? Just stumbled upon this issue and was a little surprised that it had been fixed over a year ago, but the fix has still not been released 😅
