### ISSUE TITLE
why is count way slower than wc -l ?

### ISSUE THREAD

**Issue by lunfardo** [BurntSushi/xsv#145]
So I tried this tool for the first time today. Made a quick test to see how fast it was vs linux native gnu tools, and the result was unexpected, am i doing something wrong?

[lunfardo@lunfardo-pc Datasets]$ time xsv count train.csv
125497040

real    0m8,709s
user    0m8,237s
sys     0m0,466s
[lunfardo@lunfardo-pc Datasets]$ time cat train.csv | wc -l
125497041

real    0m1,799s
user    0m0,812s
sys     0m2,404s
[lunfardo@lunfardo-pc Datasets]$ time xsv count train.csv
125497040

real    0m8,652s
user    0m8,142s
sys     0m0,503s

run xsv count twice in case it was a problem of cache or something like that.

**Comment by BurntSushi** [comment]
Because one line isn't necessarily one record? A record can span multiple lines, so counting csv records requires parsing csv records.

```
[andrew@Cheetah ~]$ cat /tmp/weird.csv
label,description
foo,"this is
one
field
really
yup"
[andrew@Cheetah ~]$ wc -l /tmp/weird.csv
9 /tmp/weird.csv
[andrew@Cheetah ~]$ xsv count /tmp/weird.csv
1
```

**Comment by lunfardo** [comment]
Upss, my bad, thank you
