### ISSUE TITLE
Non-deterministic

### ISSUE THREAD

**Issue by devinrsmith** [BurntSushi/xsv#148]
It seems like I've run into some sort of non-deterministic behavior.

My query looks like this:

```sh
{ echo '"score"' \
  & xsv select score1 scores.txt | tail -n +2 \
  & xsv select score2 scores.txt | tail -n +2; } \
  | xsv frequency -s score -l 0 \
  | xsv sort --numeric -s value
```

Essentially, I'm creating a histogram from a list of scores.

Here is partial output from run 1:
```
$ ./scores.sh
field,value,count
score,0,28051
score,1,45988
score,2,57073
score,3,60151
score,4,55674
score,5,47914
score,6,38768
score,7,29810
score,8,21805
score,9,15635
score,10,10965
```

Here is partial output from run 2:
```
$ ./scores.sh
field,value,count
score,0,28050
score,1,45988
score,2,57070
score,3,60150
score,4,55673
score,5,47912
score,6,38768
score,06,1
score,7,29810
score,8,21805
score,9,15633
score,10,10965
```

Notice that some of the counts are different, and also there seems to be a weird value "06".

[scores.txt](https://github.com/BurntSushi/xsv/files/2424898/scores.txt)

```sh
$ xsv --version
0.13.0
```

**Comment by mintyplanet** [comment]
You appear to have a bug in your script.

You want `&&` not `&` to separate your two invocations of xsv.

```bash
{ echo '"score"' \
  && xsv select score1 scores.txt | tail -n +2 \
  && xsv select score2 scores.txt | tail -n +2; } \
  | xsv frequency -s score -l 0 \
  | xsv sort --numeric -s value
```

**Comment by devinrsmith** [comment]
Ah yes, my bash scripting is a bit rusty. Thanks!
