### ISSUE TITLE
README reflect patently incorrect/invalid criticism (trivially refuted)

### ISSUE THREAD

**Issue by HerbM** [BurntSushi/xsv#153]
This issue is partially in jest, and to say thank you for producing such effective tools. 

The following criticism are almost totally invalid.

> Here are several valid criticisms of this project:
> 
>     You shouldn't be working with CSV data because CSV is a terrible format.
>     If your data is gigabytes in size, then CSV is the wrong storage type.
>     Various SQL databases provide all of the operations available in xsv with more sophisticated indexing support. And the performance is a zillion times better.
> 

CSV may be a terrible format but it exists all over the place whether one "chooses" to work with it or not -- in a corporate environment I run into it multiple times per day, e.g., downloading from corporate and government CMDB (configuration management databases) or TIcketing systems etc.)

In a small business (and corporate departmental environments) we find storing "an entire business" in Excel to be a common (terrible) practice and getting that data out to work with it or even to transfer it to a "real" database frequently requires working directly with CSV files.

Many of these cases aren't worth actually moving the data to the DB, but merely need a quick processing to provide the answer to some business or project management question.

While it's a good idea to go slow on creating NEW CSV data, even this is sometimes the easiest temporary method to move structured data between on application and another.

If the data is inherently flat (i.e., table oriented) then there is no compelling reason in most cases to adopt the extra complexity of JSoN or XML.

Tell the critics to go suck a lemon

THANK YOU.
(And thanks for RipGrep)
Even though I am a committed PowerShell user having given up almost all grep for Select-String and all Excel for CSV in favor of Import-CSV and such, I use and love ripgrep for times when it's features or speed are important. -- likely I'll feel the same about xcv)

**Comment by BurntSushi** [comment]
> Tell the critics to go suck a lemon

That's not my style. I'd just rather try to convince them.

I mean, I did write `xsv`, so I don't altogether disagree with you. I even create new CSV data occasionally. It's a useful format for representing simplistic data. Regardless, there are a lot of problems with the CSV format itself (and/or perhaps the implementations of CSV parsers), and it has been the source of much pain.
