### ISSUE TITLE
Table format to include option for setting border

### ISSUE THREAD

**Issue by keefetang** [BurntSushi/xsv#156]
Putting in a request to format the table output to include borders.

Here's a mockup with table headers.

```

┌─requestCount─┬─status──────┬─clientRequestPath────┐
│         8709 │ miss        │ /js/pacwrsmmeqsqs.js │
│          159 │ hit         │ /css/racqdsomnts.css │
└──────────────┴─────────────┴──────────────────────┘
```

**Comment by BurntSushi** [comment]
I'd rather this be done by a separate tool.

**Comment by wfxr** [comment]
Hi @keefetang , I wrote a small tool [csview](https://github.com/wfxr/csview) for viewing csv from terminal. `csview` works like python's `csvlook`, but with cjk/emoji support and performance improvement. 

I used it as a supplement to `xsv table`. Hope it can helps you :)
