### ISSUE TITLE
Feature Request, multiple inputs: xsv table file1 file2 file3 ...

### ISSUE THREAD

**Issue by peterjc** [BurntSushi/xsv#164]
I have folders of (small) tabular files which I want to be able to work on in batches, e.g.

```
$ xsv table stem*.tsv
```

Current work arounds depending the desired behaviour - treating as a simple loop:

```
$ for f in stem*.tsv; do xsv table $f; done 
```

Or, treating as continuations of the same table (same number of columns etc):

```
$ cat stem*.tsv | xsv table -d "\t"
```

In my case I am looking at files with the same headers, so either workaround is fine.

I presume any multi-file extension to ``xsv`` would be guided by what makes most sense to the tool kit as a whole (not just the ``table`` viewing command).

**Comment by peterjc** [comment]
Another example, I want to look at the first row of data after the header - this would be nice:

```
$ do xsv slice -i 0 stem*.tsv
```

Workaround:

```
$ for f in stem*.tsv; do xsv slice -i 0 $f; done 
```

**Comment by peterjc** [comment]
OK, if this is out of scope, that's fine. Thanks.

Do you want to close this issue, or add something to the documentation to help others with similar datasets?

**Comment by BurntSushi** [comment]
I don't think there's really a place for this in the docs yet. Ideally there would be a FAQ or something, but I haven't really had the bandwidth to write something. It might be better to just point to a tutorial to the basics of shell scripting. I'm just going to close this for now.
