### ISSUE TITLE
Option `--delimiter` not available in `v0.13.0` (mac)

### ISSUE THREAD

**Issue by ManavalanG** [BurntSushi/xsv#166]
I would like to use tab as delimiter, but `xsv` does not recognize option [`--delimiter`](https://github.com/BurntSushi/xsv/issues/104#issuecomment-339188785). I use `xsv v0.13.0` in MacOS Sierra `v10.12.6`.  

```
mm:~$ xsv --version
0.13.0
mm:~$ xsv --help
Usage:
    xsv <command> [<args>...]
    xsv [options]

Options:
    --list        List all commands available.
    -h, --help    Display this message
    <command> -h  Display the command help message
    --version     Print version info and exit

Commands:
    cat         Concatenate by row or column
    count       Count records
    fixlengths  Makes all records have same length
    flatten     Show one field per line
    fmt         Format CSV output (change field delimiter)
    frequency   Show frequency tables
    headers     Show header names
    help        Show this usage message.
    index       Create CSV index for faster access
    input       Read CSV data with special quoting rules
    join        Join CSV files
    sample      Randomly sample CSV data
    search      Search CSV data with regexes
    select      Select columns from CSV
    slice       Slice records from CSV
    sort        Sort CSV data
    split       Split CSV data into many files
    stats       Compute basic statistics
    table       Align CSV data into columns
mm:~$ xsv -d
Unknown flag: '-d'

Usage:
    xsv <command> [<args>...]
    xsv [options]
```

**Comment by BurntSushi** [comment]
What are you expecting `xsv -d` to do? That's not a valid command. The sub-command is what dictates which options are available. For example, if you're using `xsv select`, and you want to change the delimiter, then you'd use `xsv select -d 2 foo.csv`. Alternatively, if your file has a `tsv` extension, then a tab delimiter is used automatically.

In the future, please include more details about which commands you're trying to run. I [asked you to do that in my last correspondence](https://github.com/BurntSushi/xsv/issues/104#issuecomment-467171175) to you.
