### ISSUE TITLE
'xsv sample' always selects first row

### ISSUE THREAD

**Issue by jondegenhardt** [BurntSushi/xsv#169]
`xsv sample` always includes the first row in my tests. Example:
```
$ seq 100000 > tmp.txt
$ for i in `seq 10000`; do xsv sample 10 tmp.txt | head -n 3 >> xsv-out.txt; done
```
 The above saves the first 3 results from 10K `xsv sample` runs. Looking at the top of the file shows the first row is always selected:
```
$ head -n 20 xsv-out.txt
1
55550
35128
1
14062
51895
1
54356
47631
1
54409
21274
1
90154
68357
1
30218
93741
1
71658
```
This pattern repeats throughout the file. Changing the sample size does not affect this.
The xsv build is from the pre-built binaries on the releases page. (OS X)
```
$ xsv --version
0.13.0
```

**Comment by mintyplanet** [comment]
The first row is recognized as the column header by default.

Add `-n` or `--no-header` to ignore the header.

**Comment by jondegenhardt** [comment]
Ah, pilot error. Thanks.
