### ISSUE TITLE
Can't be used in a pipeline - doesn't support read from stdin

### ISSUE THREAD

**Issue by MrBones118** [BurntSushi/xsv#17]
My specific use case is unzip -p data.csv.zip | xsv some_transform, but more generally it'd be nice to be able to just pipe straight into xsv, to make it more unix-y

**Comment by MrBones118** [comment]
Apparently I just can't read. I was misusing xsv cat

**Comment by BurntSushi** [comment]
Indeed. Any command that can read from `stdin` will read from `stdin` if you omit the file argument.

There are some exceptions to this, like, e.g., `xsv index` which builds an index or `xsv fixlengths` without `--length`, which needs to do two passes over the data.
