### ISSUE TITLE
help <command>?

### ISSUE THREAD

**Issue by xmo-odoo** [BurntSushi/xsv#172]
`xsv help` currently shows the basic help text, however `xsv help <command>` doesn't do anything useful (shows the same), command-specific help goes through `xsv <command> —help`.

Since it already namespaces, it would be nice if `help` could be provided a command to get details, it would also be convenient when trying to find how to do something: `xsv help` to get the listing, then `<UP> <space> <command>` to get more specific help on the command.

**Comment by lienke** [comment]
Hi.
Perhaps:
`    <command> -h  Display the command help message`
cheers, lienke

**Comment by xmo-odoo** [comment]
@lienke I know that, I specifically mentioned it in the report.

What I'm saying is:
1. `help <command>` is a convenient followup to `help` as you just have to go history-up once then type the command you want help on rather than have to rewrite the entire thing
2. `help <command>` is a convenient and common helper for CLI with subcommands and even more so with a `help` subcommand.

**Comment by BurntSushi** [comment]
`xsv help` doesn't exist. It will give you same output as `xsv foobar`. That is, the output of a nonexistent command.

`xsv` doesn't need to ways of printing help info. Use `--help` instead.

**Comment by xmo-odoo** [comment]
> xsv help doesn't exist. It will give you same output as xsv foobar. That is, the output of a nonexistent command.

Did it change in master? Because as of 0.13 that's not the case at all, and `xsv [help|—help]` explicitly lists the help subcommand:
```
> xsv help

Usage:
    xsv <command> [<args>...]
    xsv [options]

Options:
    --list        List all commands available.
    -h, --help    Display this message
    <command> -h  Display the command help message
    --version     Print version info and exit

Commands:
    cat         Concatenate by row or column
    count       Count records
    fixlengths  Makes all records have same length
    flatten     Show one field per line
    fmt         Format CSV output (change field delimiter)
    frequency   Show frequency tables
    headers     Show header names
    help        Show this usage message.
    index       Create CSV index for faster access
    input       Read CSV data with special quoting rules
    join        Join CSV files
    sample      Randomly sample CSV data
    search      Search CSV data with regexes
    select      Select columns from CSV
    slice       Slice records from CSV
    sort        Sort CSV data
    split       Split CSV data into many files
    stats       Compute basic statistics
    table       Align CSV data into columns

> xsv foobar
Could not match 'foobar' with any of the allowed variants: ["Cat", "Count", "FixLengths", "Flatten", "Fmt", "Frequency", "Headers", "Help", "Index", "Input", "Join", "Partition", "Sample", "Search", "Select", "Slice", "Sort", "Split", "Stats", "Table"]
```

**Comment by BurntSushi** [comment]
Oh, interesting. Forgot about that. I'm not sure why I added that. Either way, I'm not adding support for `xsv help cmd`. Use `--help` instead.

**Comment by xmo-odoo** [comment]
Sure.
