### ISSUE TITLE
unicode issue when parsing

### ISSUE THREAD

**Issue by dnhlms** [BurntSushi/xsv#177]
I get the following error:
c:\Users\DHolmes\Downloads\DAPI>xsv slice -i 5  SalesRegions.csv
"text was not valid unicode

Notepad++ shows this file as windows CR/LF line endings and an encoding of: UCS-2 LE BOM.  I can't figure out how to get XSV to parse this file.  I also don't know if this is a bug or simply a limitation.

**Comment by BurntSushi** [comment]
When filing bugs, please do your best to provide enough data to reproduce the problem. For example, provide the input file that is causing the bug. If you can't share it, then try to create a redacted version of it such that the problem still occurs.

> Notepad++ shows this file as windows CR/LF line endings and an encoding of: UCS-2 LE BOM.

xsv doesn't know how to read UCS-2 (or UTF-16) files. You'll need to transcode them to UTF-8 first.
