### ISSUE TITLE
Quote plus newline breaks xsv fmt

### ISSUE THREAD

**Issue by alexwennerberg** [BurntSushi/xsv#186]
First off, love this tool, thanks for putting it together and maintaining it. I had an issue parsing a csv file and I'm wondering if there is a solution. I broke down the issue into a simple example.

I'm inputting a pipe delimited formatted file `sample.csv` into xsv fmt with this command:

`xsv fmt -d "|" sample.csv`

sample.csv is:

```csv
"ColA"|"ColB"
"sample"|"A
B"
"sample"|"A "B"
A"
```

The error yielded is:
`CSV error: record 3 (line: 5, byte: 45): found record with 1 fields, but the previous record has 2 fields`

It looks like the quotes plus the newline breaks xsv's parsing. I tried looking into the xsv input command for something that may help but didn't find anything. I'm not an expert on CSV, but I wonder whether this is a solvable problem? Or whether there is no real way to resolve this ambiguity. 

Thanks!

**Comment by BurntSushi** [comment]
I think the error is pretty much telling you the problem. Your last record:

```
"sample"|"A "B"
A"
```

Is malformed. You can't use quotes inside of a field without escaping them. The standard way to do this is to double them:

```
"sample"|"A ""B""
A"
```

xsv should have no issues with new lines inside of CSV fields.

**Comment by alexwennerberg** [comment]
Thanks! It looks like this is an issue with Microsoft SQL Server exporting invalid CSVs.

**Comment by BurntSushi** [comment]
Ah. Maybe look for an option to escape quotes?

**Comment by alexwennerberg** [comment]
Looks like there is none for this version of SQL Server, sadly. Ended up trying a different method of exporting data. No problem with xsv though, so I'll close this!
