### ISSUE TITLE
Feature request / community question: option not to output headers

### ISSUE THREAD

**Issue by Yomguithereal** [BurntSushi/xsv#193]
Hello everyone,

In `xsv` there is an option to ignore the input's headers, which is fine, but we don't have an option not to output the headers.

Here is why I think it could be useful: I often find myself wanting to pipe the output of a simple `xsv select` to `xargs` and friends. But the presence of the header prevents me from doing so.

Does anyone knows of a clever trick to ignore the first line of a stream (which is always a drag in unix and not straigthforward when dealing with CSV data since adventurous users may use carriage returns in header names, sigh)? Or could this be a useful addition?

**Comment by AlexMooney** [comment]
I think it would be a useful option, but you can use `xsv select … | tail -n +2` to omit the headers.

**Comment by makmanalp** [comment]
x-ref https://github.com/BurntSushi/xsv/issues/168

**Comment by joelthelion** [comment]
Why was this closed? This would be very convenient.

**Comment by n8henrie** [comment]
> | tail -n +2

As an alternative, `xsv slice -n --start=1` is working for me.

**Comment by nk9** [comment]
Agreed, this would be very nice. Seems an obvious time saver.
