### ISSUE TITLE
Feature request: a one-line command to turn any CSV into a simple web service?

### ISSUE THREAD

**Issue by breck7** [BurntSushi/xsv#195]
For Ohayo there are dozens/hundreds/thousands of medium to large (5MB - 500MB) public domain csv files I'd like to provide people with instant access to. What if it were as easy as this:

```
xsv serve worldcitiespop.csv 3000
```

```
wget http://localhost:3000/headers
```

Response:
```
1   Country
2   City
3   AccentCity
4   Region
5   Population
6   Latitude
7   Longitude
```

I could see the argument that it would be smarter to wrap this, but I could also see this being so useful that it may make sense to include it as a core feature.

Thoughts?

**Comment by BurntSushi** [comment]
xsv has no al business performing network calls, and I'd like to keep it that way. Sorry.

**Comment by breck7** [comment]
@BurntSushi makes total sense. I'm going to experiment and wrap XSV to accomplish this (https://github.com/treenotation/datasets)
