### ISSUE TITLE
Thank you! :)

### ISSUE THREAD

**Issue by swayson** [BurntSushi/xsv#203]
As a weekly user of `xsv` I would like to take this opportunity to thank the maintainer and other contributors. You folks have made working with CSV files a joyous experience, which I didn't even know if it could be possible :) 
Seriously, it is exceptional and I one of the first tools I install on a fresh machine/env. 

Thank you for making delightful software.

**Comment by BurntSushi** [comment]
Thanks! I really appreciate the kind words. :-)
