### ISSUE TITLE
Feature Request:  CSVCLEAN Port

### ISSUE THREAD

**Issue by dfirence** [BurntSushi/xsv#221]
Hi,

Would it be possible for you to add as a feature a CSVCLEAN approach like the python CSVKIT utility called CSVCLEAN?

**Comment by BurntSushi** [comment]
This feature request is not actionable. Please provide more details. Please provide as much of a specification as possible for the feature you're asking for.

**Comment by dfirence** [comment]
> As a XSV USER I need to validate the csv is clean of any errors. 

When running a command from XSV, I would like XSV to inspect and report to me the csv is clean. 

If the csv has incorrect number of expected columns, I would like XSV to identify that data format error and remove the dirty lines leaving a good csv file.  

This type of feature is provide by the Python CSVKIT package.

**Comment by BurntSushi** [comment]
Sounds line you want `xsv fixlengths`, which already exists.

**Comment by dfirence** [comment]
Thank YOU! I love this tool
