### ISSUE TITLE
hyphen not recognised in column headers

### ISSUE THREAD

**Issue by gennaro-tedesco** [BurntSushi/xsv#222]
Whenever column headers present hyphenation, they are not recognised by the `xsv select` statement.

Consider the below `example.csv`

```
first,second-column
a,b
``` 
this generates:
```
xsv headers example.csv
1   first
2   second-column
...
xsv select first,second-column example.csv
Selector name 'second' does not exist as a named header in the given CSV data.
```
whereas such error disappears if the hyphen is changed into an underscore or any other non-alphanumerical character.

Specifics: I am running `xsv --version 0.13.0` on a macOS Catalina 10.15.4

**Comment by Yomguithereal** [comment]
Hello @gennaro-tedesco. That's because the `-` char is used to select a range of columns, for instance:

```
xsv select 1-4 file.csv
```

So, as `xsv select -h` indicates, you need to write your column likewise:

```
xsv select 'first,"second-column"'
```
