### ISSUE TITLE
Is the project dead ? 

### ISSUE THREAD

**Issue by mishaker** [BurntSushi/xsv#225]
Hello @BurntSushi , 
Do you still maintain the project ? If not, are you willing to give access to other people? 
I see a lot of useful PRs and great ideas. 
But they are ignored. 
Not much activity since last year. 

Please let us know :)
Thanks

**Comment by BurntSushi** [comment]
I am spread pretty thin between a lot of projects. I do _plan_ on attending to xsv at some point in the future, but I don't know when.

I will not be giving access to the project by others. I'm not necessarily opposed to doing it, and I've done it many times in the past for other projects. Handing projects over to others has _mostly_ resulted in failures with one or two success stories. This has caused me to raise my bar for when I'm willing to do this. At this point, I'd only hand it over to someone I trust and/or who has an established public track record of open source contribution.

All that being said, I still have a vision for the future direction of this project, so I'd prefer to keep it under my direction for now. I understand that some people want a more active maintainer though. If so, I'd suggest a project fork with a new name.

**Comment by mishaker** [comment]
Thanks for your answer !

**Comment by vi** [comment]
Note: there seems to be a fork of xsv named [qsv](https://github.com/jqnatividad/qsv).
Forking reasons include merging pending PRs to xsv.

Maybe fork author can be added to maintainers of xsv?

**Comment by BurntSushi** [comment]
> Maybe fork author can be added to maintainers of xsv?

https://github.com/BurntSushi/xsv/issues/225#issuecomment-631463846
