### ISSUE TITLE
xsv sort returns SIGKILL on alpine for large files

### ISSUE THREAD

**Issue by willfarrell** [BurntSushi/xsv#232]
I'm running `xsv sort -s Column2,Column1 /mnt/data/file.csv > /mnt/data/file-sort.csv` in docker (alpine) on various files sized (1KB - 4GB). Smaller files sort just fine, large files return `SIGKILL` w/o any `stderr`. I'm triggering from node v12. Wondering if anyone else has run into this?

Dockerfile
```Dockerfile
FROM node:12-alpine AS build

RUN apk update && \
    apk add --no-cache cargo git && \
    cd / && \
    git clone git://github.com/BurntSushi/xsv && \
    cd xsv && \
    cargo build --release

FROM node:12-alpine
COPY --from=build /xsv/target/release/xsv /usr/local/bin/xsv

...

CMD ["node","--max-old-space-size=1600","index.js"]
```

index.js
```nodejs
const promisify = require('util').promisify
const exec = promisify(require('child_process').exec)

const sortFile = async (from, to) => {
    return exec(`xsv sort -s ${sortKeys.join(',')} ${from} > ${to}`)
}
```

**Comment by BurntSushi** [comment]
Check dmesg. Your OS is almost certainly killing the process for using too much memory.

**Comment by willfarrell** [comment]
Thanks for the quick reply, I'll focus my investigation there.

**Comment by willfarrell** [comment]
Upping the memory fixed it just like that. Thanks.
