### ISSUE TITLE
Feature suggestion: replace 0x0A 0x0D inside fields with spaces

### ISSUE THREAD

**Issue by cpkio** [BurntSushi/xsv#233]
Multiline CSVs have CR or LF chars inside a properly quoted field. As far as I can see with 0.13.0, `xsv` breaks on those. How about an option of automatically replacing CRLF (for processing only) with spaces?

**Comment by Yomguithereal** [comment]
Can you paste a minimal example that break here?

**Comment by cpkio** [comment]
This is a small 3-piece sample [product_sample_cp1251.zip](https://github.com/BurntSushi/xsv/files/5007708/product_sample_cp1251.zip). File encoding is CP1251 (Windows Cyrillic). The fields are not quoted, because there's no quote chars or separator symbols inside. Some fields contain 0x0A as a line break symbol (happens in real data). The CSV has CRLF endings though.
```
xsv stats -d ';' .\product_names_sample.txt
CSV error: record 1 (line: 1, byte: 64): found record with 2 fields, but the previous record has 8 fields
```

My point is 1) CR or LF by itself should be fine in a nonquoted field, if CSV has CRLF endings; 2) these multiline fields should be compressed to one line (replace line breaks with spaces) for the purpose of viewing in xsv output.

**Comment by BurntSushi** [comment]
> CR or LF by itself should be fine in a nonquoted field

CR should be, but LF is not and this is not going to change. Sorry. You need to quote line-endings.
