### ISSUE TITLE
Feature: Add option to specify number of header rows

### ISSUE THREAD

**Issue by belst** [BurntSushi/xsv#245]
I have some csv files where the headers are 2 rows. It would be really nice if I could specify somewhere that the first 2 rows are headers and not just the first.

**Comment by Yomguithereal** [comment]
How does this work @belst? Can you show us an example, I am curious :)? Is the second row to be ignored somehow then? In this case I guess you can make *some* things work using `xsv slice`, no?

**Comment by belst** [comment]
I guess ignoring the 2nd row would work in some cases. Atm I am working with files which have the unit of the measurements in the second row eg:

```csv
Datetime;Measurement1;Measurement2
;[°C];[K]
2020-08-14 22:00:00;256.698;0.3722
```

for most operations slicing would work but for example when concatenating files I would want the names with the units at the top and just concatenate the values.

Right now just running `cat` would intersperse the units in the file.

**Comment by Yomguithereal** [comment]
I had never seen this kind of CSV files yet. Does not mean it is not valid, though. I guess that with some bash magic you could xsv cat slices of files avoiding the first two rows and prepending your two lines of headers on top with a regular cat. But it starts to be a bit contrived indeed.

**Comment by BurntSushi** [comment]
Sorry, but I don't think xsv should support this. The amount of work required to do this isn't worth it IMO.
