### ISSUE TITLE
Create a new release?

### ISSUE THREAD

**Issue by jqnatividad** [BurntSushi/xsv#256]
Since 0.13.0 came out in May 2018, [several xsv improvements have been made](https://github.com/BurntSushi/xsv/compare/0.13.0...master) (sample --seed, partition, reverse, etc. ) and even the README refers to some of these new capabilities.

Can you bump the version and release new binaries?

**Comment by BurntSushi** [comment]
I'd like to, but I don't know when I'll find the time. Sorry. Until then, compile from master.

**Comment by peterjc** [comment]
Also transpose (#137 / #146) would be in the next release.
