### ISSUE TITLE
[Windows] error: unresolved name `libc::GetSystemInfo`

### ISSUE THREAD

**Issue by m-n** [BurntSushi/xsv#26]
XSV is failing to build on Windows:

    src\util.rs:17:9: 17:30 error: unresolved name `libc::GetSystemInfo` [E0425]
    src\util.rs:17         ::libc::GetSystemInfo(&mut sysinfo);

That's from `num_cpus`. If I hard code `num_cpus` to return `4` it builds fine. 

It looks to me like `GetSystemInfo` was removed from `libc` for Windows on [this commit](https://github.com/rust-lang-nursery/libc/commit/c4d4c70a36f82186f259fb6816b0b87997633940).

**Comment by BurntSushi** [comment]
OK, this should be all set. I also added CI for Windows so that it won't be so easy to break in the future.

**Comment by m-n** [comment]
Thanks, that was fast :+1:
