### ISSUE TITLE
need help on concat two columns into one

### ISSUE THREAD

**Issue by verajosemanuel** [BurntSushi/xsv#265]
for processing a large file and compose a key I need to concat two columns into one.

```
# from this
header1,header2,header3
A,1,Hello
A,2,Bye

# to this

newHeader1,header3
A1,Hello
A2,Bye
```

any suggestion?

**Comment by BurntSushi** [comment]
xsv can't perform arbitrary manipulation of CSV data. You'll need to write a program.
