### ISSUE TITLE
get rid of quotation when using partition by column

### ISSUE THREAD

**Issue by verajosemanuel** [BurntSushi/xsv#266]
I have a CSV with many columns. One of them is a long string using xml format.
I want to partition by ID but the output files are filled with lots of quotes.

How to avoid this behaviour?

```
xsv select myId,xml_content | xsv partition --filename part{} myId

myId,xml_content
1,"<isnew value=""""/><email value=""""/><city value=""""/>"
```

Desired output

```
myId,xml_content
1,<isnew value=""/><email value=""/><city value=""/>

```

**Comment by BurntSushi** [comment]
Your desired output is invalid CSV.

**Comment by verajosemanuel** [comment]
I know, but I am forced to work with it. So any suggestion on gettin rid of double quotation when partitioning would be great

**Comment by BurntSushi** [comment]
xsv can't do it. You'll have to write your own program to output non-CSV data.
