### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by MatthiasKauer** [BurntSushi/xsv#27]
Hi,
I'm wondering if a windows binary is currently on the agenda. I have tried compiling the project there a while ago, but ran into some issues. I wanted to follow up on that once I understood Rust a bit more.

Last week, I saw you added AppVeyor CI and thought you would release a Windows binary any moment now. It's been almost 2 weeks now, however, so I feel that there is a chance you have missed the artifacts feature of Appveyor that lets you download the binaries it compiles.

Would you be interested in a pull request in that direction? I assume you didn't already hit a wall with that attempt...

Kind regards,
Matthias

**Comment by BurntSushi** [comment]
I would be very happy to accept a pull request! I haven't done anything in that direction yet, I'm only using appveyor to run tests and make sure it builds.

**Comment by MatthiasKauer** [comment]
I have made some headway now, but also encountered some questions:
First of all, the exe to be downloaded here seems to work on my Win7 machine: https://ci.appveyor.com/project/MatthiasKauer/xsv/build/1.0.4/job/qi3yejo1hgoom05v/artifacts
(I appended mingw locally to distinguish the exe file from MSVC version).
```
C:\opt\xsv>xsv-mingw.exe stats worldcitiespop.csv --everything | xsv-mingw.exe table
field       type     min            max            min_length  max_length  mean                stddev              median      mode         cardinality
Country     Unicode  ad             zw             2           2                                                               cn           234
City        Unicode   bab el ahmar  Þykkvibaer     1           91                                                              san jose     2351892
AccentCity  Unicode   Bâb el Ahmar  ïn Bou Chella  1           91                                                              San Antonio  2375760
Region      Unicode  00             Z9             0           2                                                   13          04           397
Population  Integer  7              31480498       0           8           47719.570633597126  302885.5592040396   10779                    28754
Latitude    Float    -54.933333     82.483333      1           12          27.188165808468785  21.95261384912504   32.4972221  51.15        1038349
Longitude   Float    -179.9833333   180            1           14          37.08885989656418   63.223010459241635  35.28       23.8         1167162
```
The Visual Studio version requires a runtime for Visual Studio 2015 that I currently do not have. This brings up my first question:
Should we downgrade to VS 2013 which is the minimum for Rust for increased compatibility, just continue VS 2015 and require one more dll install that one will have to do eventually anyway as more projects adopt VS 2015, or should we only build MingW?

Another question is whether I need to run tests with the debug build. 
Does
```
cargo build --release
cargo test --release
```
give equivalent / sufficient coverage?
The builds are quite long and we're approaching the 60min limit with both debug and release build. And of course we shouldn't waste the resources of generous folks for no reason either :)

One more thing: I encountered one failing test here: https://ci.appveyor.com/project/MatthiasKauer/xsv/build/1.0.2
```
test test_frequency::prop_frequency_indexed ... thread 'safe' panicked at 'assertion failed: `(left == right)` (left: `[("(NULL)", 51), ("\u{3a7e}", 1), ("\u{5380}", 1), ("\u{81f5}", 1), ("\u{1188e}", 1), ("\u{16c75}", 1), ("\u{17107}", 1), ("\u{27803}", 1), ("\u{3c67e}", 1), ("\u{43e16}", 1), ("\u{4f86e}", 1), ("\u{5b293}", 1), ("\u{5d5a5}", 1), ("\u{64df4}", 1), ("\u{65b18}", 1), ("\u{66c0a}", 1), ("\u{682a4}", 1), ("\u{712ad}", 1), ("\u{73115}", 1), ("\u{87644}", 1), ("\u{8f62d}", 1), ("\u{905a4}", 1), ("\u{9bca9}", 1), ("\u{a86b9}", 1), ("\u{a887c}", 1), ("\u{aa456}", 1), ("\u{af023}", 1), ("\u{b3daa}", 1), ("\u{b68e4}", 1), ("\u{c8336}", 1), ("\u{c8999}", 1), ("\u{d15b9}", 1), ("\u{d6394}", 1), ("\u{db490}", 1), ("\u{e5416}", 1), ("\u{e9503}", 1), ("\u{ea58e}", 1), ("\u{f6e51}", 1), ("\u{fb059}", 1)]`, right: `[("(NULL)", 50), ("\u{2005}", 1), ("\u{3a7e}", 1), ("\u{5380}", 1), ("\u{81f5}", 1), ("\u{1188e}", 1), ("\u{16c75}", 1), ("\u{17107}", 1), ("\u{27803}", 1), ("\u{3c67e}", 1), ("\u{43e16}", 1), ("\u{4f86e}", 1), ("\u{5b293}", 1), ("\u{5d5a5}", 1), ("\u{64df4}", 1), ("\u{65b18}", 1), ("\u{66c0a}", 1), ("\u{682a4}", 1), ("\u{712ad}", 1), ("\u{73115}", 1), ("\u{87644}", 1), ("\u{8f62d}", 1), ("\u{905a4}", 1), ("\u{9bca9}", 1), ("\u{a86b9}", 1), ("\u{a887c}", 1), ("\u{aa456}", 1), ("\u{af023}", 1), ("\u{b3daa}", 1), ("\u{b68e4}", 1), ("\u{c8336}", 1), ("\u{c8999}", 1), ("\u{d15b9}", 1), ("\u{d6394}", 1), ("\u{db490}", 1), ("\u{e5416}", 1), ("\u{e9503}", 1), ("\u{ea58e}", 1), ("\u{f6e51}", 1), ("\u{fb059}", 1)]`)', tests\test_frequency.rs:230
....
```
This may have been a fluke. It didn't show up in later attempts anymore.
Through all this, I haven't touched the code itself in anyway, only the appveyor.yml.

**Comment by BurntSushi** [comment]
I'd still like this, and I think the flaky test should be fixed now.

I'm not sure how to answer your Windows specific questions though.

`cargo build --release` should be used to produce the final binary and `cargo test` will run the full test suite.

**Comment by MatthiasKauer** [comment]
Thanks for the clarifications. I'm also still interested in this.
I gotta admit that I haven't touched Rust in a bit, but I'll see what I can do here :)

**Comment by BurntSushi** [comment]
@MatthiasKauer Oh! I forgot to close this ticket because Windows binaries are [now available](https://github.com/BurntSushi/xsv/releases). :-) I got it done thanks to the https://github.com/japaric/rust-everywhere project.

**Comment by MatthiasKauer** [comment]
Oh. That's great too. rust-everywhere looks like a very systematic project :+1:
