### ISSUE TITLE
xsv frequency: show > 10 lines

### ISSUE THREAD

**Issue by gennaro-tedesco** [BurntSushi/xsv#270]
Apparently `xsv frequency <filename>` defaults to showing the 10 topmost results: is there an option to relax it and show the full frequency counts?

**Comment by BurntSushi** [comment]
`xsv frequency --help` should pretty clearly point to the `-l/--limit` flag for exactly that purpose.

**Comment by gennaro-tedesco** [comment]
Sorry, my bad completely, it was in fact laid plainly there. Thank you for the quick reply and for the awesome `xsv`!
