### ISSUE TITLE
[Suggestion] More resilient input handling

### ISSUE THREAD

**Issue by hktonylee** [BurntSushi/xsv#280]
I must say `xsv` is really useful tool! However I have one issue that some of my CSV files do not have enough fields. Let's say for this

```csv
col1,col2,col3
v1,v2
v3,v4
v5,v6
```

`xsv` will throw error `CSV error: record 1 (line: 2, byte: 15): found record with 2 fields, but the previous record has 3 fields`

My suggestion would be to throw warning instead, and still read the CSV as if the column is empty. This can help people to process some broken (and large) CSV file.

**Comment by BurntSushi** [comment]
Try the `xsv fix-lengths` command.

**Comment by hktonylee** [comment]
Thank you! This is a good solution :)

**Comment by nezda** [comment]
Now it's `xsv fixlengths` (no `-`)
