### ISSUE TITLE
Transformation changes CSV file encoding

### ISSUE THREAD

**Issue by theogaraj** [BurntSushi/xsv#287]
Hello, first of all, thank you so much for creating such a great tool!  I do a lot of CSV data wrangling and this has been very helpful.

**Issue:**  Using xsv to select specific columns from a csv file and write them to a new file; original csv is us-ascii but the new file is utf-16le.

**Command:**  `xsv select 1,2,6,7,8 file_1.csv > file_2.csv`

**Environment:**  Windows 10 (running in Powershell).

**Observations and other info:**

- If I switch to a bash shell and run the same command I see that the resulting file remains us-ascii.
- I'm using file -i <filename> within bash to determine the file encoding.
- This appears to be something due to Windows.  I tried changing the code page using `chcp 65001` (original was 437) but that didn't seem to change things.

I don't know that I'd call this an "issue" as I'm able to achieve my goal by switching to bash.  But I'm curious why it happens and if there's just something simple I'm missing that can save me having to switch.

**Comment by BurntSushi** [comment]
I have no idea personally. I don't use Windows and don't understand why the file encoding would change on you silently. You'll need to talk to Windows experts.

**Comment by theogaraj** [comment]
Thanks for the quick response.  Closing this out as I'm able to get it to work by switching to a bash shell.  Hope this is useful for others who are facing a similar problem.
