### ISSUE TITLE
Completions

### ISSUE THREAD

**Issue by DanielRivasMD** [BurntSushi/xsv#297]
Feature request

**Comment by paw-lu** [comment]
This is marked as completed, but i'm not sure how to enable completions 😅. Any hints?

**Comment by NateEag** [comment]
@paw-lu Came looking for this myself - seems like [this](https://github.com/docopt/docopt.rs?tab=readme-ov-file#tab-completion-support) might do the job?

I'm not a Rustafarian, so didn't take the time to try
