### ISSUE TITLE
Scanning of "cargo-geiger" showed unsafe code 

### ISSUE THREAD

**Issue by vidhyasasi** [BurntSushi/xsv#319]
Hi,
I scanned the tool "cargo-geiger"(https://github.com/rust-secure-code/cargo-geiger) on xsv to find the usage of unsafe code in the package. It  showed the statistics that a lot of code in the package has unsafe code. The screenshot of result is given below
<img width="580" alt="Screenshot 2023-04-27 at 09 44 09" src="https://user-images.githubusercontent.com/64778227/234794580-635589e0-5bfe-4812-944e-d1cd38cf1d63.png">

It would be helpful of you could fix this issue!
System info - debian11
xsv version - 0.13.0

Thanks!

**Comment by BurntSushi** [comment]
See https://github.com/BurntSushi/ripgrep/issues/2499#issuecomment-1525579612.
