### ISSUE TITLE
Feature request: Case insensitive regexp search

### ISSUE THREAD

**Issue by Armavica** [BurntSushi/xsv#32]
Amongst the widely used options of `grep` and other regexp-based search programs is `-i, --ignore-case`, which allows to ignore case distinctions in the regexp pattern as well as in the input. I think that adding it to the `search` command would be a nice enhancement since it implements a feature not easily achievable in other ways, and most people (I guess) are already familiar with it from using `grep` or others (and could maybe even actually expect its presence in such a context).

**Comment by BurntSushi** [comment]
@Armavica A case insensitive option is probably a good idea. For now, you can use `(?i)pattern`.

**Comment by BurntSushi** [comment]
@Armavica Even though this was always possible, `-i` is a much more expected interface, so I've added it. Thanks!
