### ISSUE TITLE
What should print `search` on an empty search?

### ISSUE THREAD

**Issue by Armavica** [BurntSushi/xsv#33]
I often chain several searches with pipes:

```
$ echo -e "foo,bar\nbli,blo" | xsv search -s foo bla | xsv search -s bar blo
Selector name 'bar' does not exist as a named header in the given CSV data.
```

Here, the first search does not find any result, so nothing is sent to the second one, which will issue a warning because the column `bar` is not defined any more. Isn't it a bit strange, semantically? Especially in comparison to `stats` or `frequency` which always print a header line even on an empty input. Shouldn't `search` always print the headers line of the input file as well?

**Comment by Armavica** [comment]
Maybe this is just a theoretical folly, but if you define the _type_ of a CSV file by its header, then you can also type the functions `search`, `frequency` and `stats`.  While `frequency` and `stats` take any type and return respectively the `field,value,count` type and the `field,[...],stddev` type, it is reasonable to think that `search` should conserve the type of its argument: `search: 'a -> 'a`.  I guess then that the question boils down to the highly fundamental issue of the type of the empty CSV file. :smile:

**Comment by BurntSushi** [comment]
I think practical considerations and consistency trump type theory in the case of this tool. I do think `xsv search` should probably print something sensible to enable what you're trying to do.

**Comment by Armavica** [comment]
> I do think xsv search should probably print something sensible to enable what you're trying to do.

Like the header row even if the search is unsuccessful?

**Comment by BurntSushi** [comment]
@Armavica This should be fixed. Headers are always shown even if there were no matching rows. (Amusingly, the code was going out of its way to *not* show the headers when no results were found.)
