### ISSUE TITLE
Getting sum of a column

### ISSUE THREAD

**Issue by eliangcs** [BurntSushi/xsv#34]
When I do `xsv stats -s COLUMN --everything FILE`, the metrics I can see are min, max, min_length, max_length, mean, stddev, median, mode, and cardinality. How can I get sum? Is it unimplemented or hiding somewhere?

BTW, thank you for the nice work!

**Comment by BurntSushi** [comment]
It doesn't exist. You can see the source for that command here: https://github.com/BurntSushi/xsv/blob/master/src%2Fcmd%2Fstats.rs

**Comment by eliangcs** [comment]
Then I'd like to make this a feature request :)

**Comment by BurntSushi** [comment]
@eliangcs Sums are now included in the standard statistics output. Thanks!

**Comment by eliangcs** [comment]
Works perfectly, thanks!
