### ISSUE TITLE
xsv search should be type aware (e.g., for comparing numeric values)

### ISSUE THREAD

**Issue by vi** [BurntSushi/xsv#35]
SELECT, JOIN and ORDER BY seems to be already in, but filtering rows (WHERE) or replacing groups of rows with stats seems not to be implemented.

I expect the interface to be like this:

    xsv filter Population lt 1000 worldcitiespop.csv | xsv group Region | xsv select Region,Latitude/avg,Longitude/median | xsv table

Can xsv eventually replace [q](https://github.com/harelba/q)?

For fun: my most complicated `q` usage is this:

    q 'SELECT COUNT(a.c3),SUM((a.c3 - b.c3)/1000/1000),SUM((a.c3 - b.c3)/1000/1000*(a.c3 - b.c3)/1000/1000) FROM l.txt a INNER JOIN l.txt b ON a.c2 = b.c2 WHERE a.c1 = "o" AND (b.c1 = "s" OR b.c1 = "i")'

**Comment by BurntSushi** [comment]
If you want to use SQL, then `xsv` probably isn't the right command for you. I'd recommend loading your data into a SQLite database and running SQL commands there.

> but filtering rows (WHERE)

That's not true. `xsv search` supports filtering.

I'm not intrinsically opposed to your suggestions, but I'm unlikely to implement them myself.

**Comment by vi** [comment]
How do I compare numbers in `xsv search`? For example where one field is more than another field?

**Comment by BurntSushi** [comment]
You can't, but that doesn't mean `xsv` can't do filtering. There are also a number of joins that xsv can't do, and a number of different types of sorts that xsv can't do, and yet, it still does joins and sorting.

**Comment by BurntSushi** [comment]
`q` is a really cool project, but it's not something I'm likely to either invest in or maintain for `xsv`.

I'm open to possibly expanding the functionality of `xsv search` to be type aware, but I'd like to brainstorm ideas for the interface first.

**Comment by BurntSushi** [comment]
Closing in favor of #31.
