### ISSUE TITLE
How do I "unflatten" the data?

### ISSUE THREAD

**Issue by vi** [BurntSushi/xsv#36]
I expected something like

    for i in /proc/*/status ; do cat "$i"; echo '#'; done | xsv unflatten | xsv sort -s Threads: | xsv select Name:,Threads:

Can I also override row separator to handle `/proc/*/environ` or `find -print0`?

**Comment by BurntSushi** [comment]
I don't know what "unflatten" means in this context. You'll have to explain more. It sounds like you're trying to read data that isn't CSV, so I'm not sure why you would expect `xsv` to work with it.

The row separator cannot be changed, although such an option should be added to the `xsv input` command.

**Comment by vi** [comment]
It meant turning data produced by `xsv flatten` back into csv.

**Comment by BurntSushi** [comment]
`xsv flatten` (like `xsv table`) is meant for *displaying* CSV data to a human in a way that may be more convenient than its raw form.

`xsv` is not a general purpose tool for parsing arbitrary text formats.
