### ISSUE TITLE
How can one add quotes to output

### ISSUE THREAD

**Issue by patricebellan** [BurntSushi/xsv#37]
Hi,
I'm fairly new to using xsv so may have missed something,
but I couldn't figure how I could force it to surround all values with double quotes when exporting data.

Is there an option I missed?

**Comment by BurntSushi** [comment]
That option doesn't exist. What problem are you trying to solve?

**Comment by patricebellan** [comment]
I'm using xsv to join different CSV files to build an output file I'll then feed to a tool.
But this tool requires my CSV files to have double quotes around everything.

So I was able to build all the data I need very easily, but I'm currently stuck.
I can reformat the CSV with other unix tools, but I'll need to reprocess a few million rows while more formatting options in xsv would do the trick in one pass.

**Comment by BurntSushi** [comment]
@patricebellan I've added a `--quote-always` flag to the `xsv fmt` command which should do what you want. e.g.,

```
$ cat > test.csv <<EOF
> abc,xyz
> EOF
$ xsv fmt --quote-always test.csv 
"abc","xyz"
```

**Comment by patricebellan** [comment]
I updated and tested and this is indeed exactly what I needed, thanks a lot!
