### ISSUE TITLE
Support for tsv as output

### ISSUE THREAD

**Issue by pwaller** [BurntSushi/xsv#41]
Using `xsv sample -d $'\t'` it correctly reads a TSV (Tab Separated Values) input, but then writes CSV as output. In my case I want to keep the input format and sample it.

An option to control the output delimeter would be very useful.

**Comment by BurntSushi** [comment]
This is already supported with the `xsv fmt` command. e.g., `xsv sample -d '\t' | xsv fmt -t '\t'`.

**Comment by BurntSushi** [comment]
Oh, @pwaller, one thing you may find useful is naming your files with a `.tsv` extension. I think `xsv` should then automatically use the `\t` delimiter for reading/writing.

**Comment by pwaller** [comment]
Ah @BurntSushi thanks! I was using stdin/stdout so didn't discover this.
