### ISSUE TITLE
Partition into files based on columns?

### ISSUE THREAD

**Issue by emk** [BurntSushi/xsv#51]
Wow, `xsv` is cool!

I was exploring [Pachyderm](https://www.pachyderm.io/) for large-scale data ingestion tasks, and one use-case popped up fairly often. This is basically a map/reduce implementation using an immutable, versioned cluster file system, and worker jobs running inside of Docker containers. You read files from `/pfs/$INPUT_NAME/*` and write them to `/pfs/out`.

Imagine an input file which looks like:

```
value,count
FL,11957
CA,11816
TX,10157
IL,5633
OH,5556
GA,4535
NY,4088
MI,4008
NJ,3890
CO,3690
```

I would love to be able to write something like:

```
xsv partition value /pfs/out
```

...and create a file named `/pfs/out/FL` containing `11957`, a file named `/pfs/out/CA` containing `11816`, and so on. It would also be OK if the files contained the partitioning column: `FL,11957` and `CA,11816`. If there are more than two columns, they should all be included. All rows with the same `value` column should be in the appropriate output file.

Does `xsv` have support for anything like this? Would you _like_ support for something like this? If not, no worries, it would be a trivial standalone tool using your `csv` library. But I thought I'd check whether you wanted it upstream first.

**Comment by BurntSushi** [comment]
I think the only command that splits CSV files into many CSV files is the `xsv split` command, but I don't think it can be made to work for your use case here.

I do think an `xsv partition` command that works like you describe would be useful though and pretty easy to implement. :-) If you'd like to submit a PR for it, then I'd be glad to accept it. My only request is that you look at `xsv split` and see if you can use a similar interface. e.g., `xsv partition <outdir> <column> [<input>]`.

The natural question to ask here is: does partitioning ever make sense for more than one column at the same time? (I think we can punt on answering that question though, since it seems like a backwards compatible change.)

**Comment by emk** [comment]
I think partitioning for multiple columns is perfectly reasonable. People will expect it to work in any case.

Some further thoughts since last night:

1. I'd love to use field values to build the output filenames, as above, because it makes it very easy to see what's going on. But the namespace for valid file names is more restrictive than the values of CSV fields. Also, output filenames probably need to be "shell safe", because I just _know_ somebody is going to try to glob these output files with a shell script at some point. This means any "/" in the data definitely needs to be removed from the file name, but also probably any "$", " ", etc.  So we could either name the files with sequential numbers (which makes it harder to inspect the partitions), or we could use a whitelisted charset to build a "safe" filename. We should think about this. I'm definitely open to ideas here!
2. Since the file name is at best an approximation of the value in the partition field, we want to keep all input columns _including_ the partition key in the output. This also means it matters less if two partition keys map to the same filename.

Please feel free to tell me I'm confused. :-) This is all experimental.

**Comment by BurntSushi** [comment]
> I'd love to use field values to build the output filenames, as above, because it makes it very easy to see what's going on.

Right. I would personally be in favor of doing something very simple here. Maybe something like this:

```rust
let utf8name = String::from_utf8_lossy(value);
let re = Regex::new(r"\W").unwrap();
let mut file_name = re.replace_all(&utf8name, "");
if file_name.is_empty() {
    file_name = <some short random string>;
}
```

Basically, assume the value is close to UTF-8 and then strip anything that isn't a Unicode word codepoint.

I think using some heuristic like the above is a lot better than switching to something opaque like sequential numbers, since a heuristic will probably almost always work and we therefore wind up with a better UX.

> Since the file name is at best an approximation of the value in the partition field, we want to keep all input columns including the partition key in the output. This also means it matters less if two partition keys map to the same filename.

Yes, we should definitely include the partition key even if the only reason is that it is trivial to remove it after-the-fact with `xsv select`.

Having two distinct partition values map to the same filename seems unfortunate, but it's probably not worth trying to complicate our heuristic to fix it unless there's a straight-forward way to do it. Maybe by adding sequential numbers to the end of the name. :P

**Comment by emk** [comment]
> Having two distinct partition values map to the same filename seems unfortunate, but it's probably not worth trying to complicate our heuristic to fix it unless there's a straight-forward way to do it. Maybe by adding sequential numbers to the end of the name. :P

It sounds like we might want a `HashMap` from field values to filenames, then, which would make it easier to do things like remember which sequential number to use for two colliding values.

Also, do you have any strong opinions on file extensions? Should we just use `.csv` for all output files? Or write them without an extension? We can always add a flag later if necessary, but I'd prefer to just pick a sensible default.

Another interesting puzzle is how to name files with a multi-column partition:

```
xsv partition outdir State,Zip
```

...might generate either `CA_90210.csv` or `CA,90210.csv`. Probably `_` is safer. We could just join the selected field values together with `_` and then look up our filename.

Finally (yes, one more thing!), the natural implementation of this would use lots of open `File` objects, one per output stream. It seems like the default Linux limits are:

```
Limit                     Soft Limit           Hard Limit           Units     
Max open files            1024                 65536                files      
```

So we might hit a ceiling around 1024 partitions (varying by OS) where we either need to get clever about opening and closing files, or we need to call `setrlimit` to raise the soft limit (which is allowed for regular processes without root permissions). Actually we have a potential real-world use-case involving a zipcode partition, so this isn't a purely hypothetical question.

On Windows, the default limit is 512 and [it can be bumped to 2048](https://msdn.microsoft.com/en-us/library/6e3b887c(vs.71).aspx). Hmm.

Anyway, I'll try to take a crack at this soon. Should be fun. :-)

**Comment by BurntSushi** [comment]
@emk Hmm, yes, looks like you have your work cut out for you. :-) I would be OK with taking reasonable shortcuts for some of those issues (like not doing multi-column partitions or handling the file descriptor limits) based on how much work/effort you want to put into this.

For the file extension, I think just using `.csv` for now is fine. It's what `xsv split` does. There are arguably better choices (like making it configurable through a flag or by using the same extension as the input, if the input is a named file), but starting with `.csv` seems fine.

**Comment by emk** [comment]
OK, cool. :-)

> For the file extension, I think just using .csv for now is fine.

I had an internal discussion and stared some more at the Pachyderm docs, and I think it might actually be useful to have something like:

```
--filename TEMPLATE   Filename template to use for output files (default: {}.csv)
```

This would allow changing the extension, but also things like `xsv partition --filename 'state-{}.csv' out/ State` (which allows multiple partitions to be dumped into the same directory) or `xsv partition --filename "{}-$(uuid)" out/ Zip` (which allows multiple `xsv partition` processes to write to the same output namespace, which looks like it might be important for feeding mapper output into reducers). Basically this handles at least three use cases with one natural-looking flag, which is always nice. 🙂

Or maybe the syntax should just be `xsv partition 'out/{}.csv' Zip`, but then we would want to be sure it was consistent with `xsv split`? So maybe a `--filename` option is the right way to go.

Anyway, I'd implement this in stages, starting with the easy parts first.

**Comment by BurntSushi** [comment]
I think a `--filename` flag is fine, and I do prefer that than requiring the user to specify a template.

I'm also OK with a template so long as it remains simple. These types of features have a way of getting bloated though, so be careful. :-)
