### ISSUE TITLE
Request to add -t for tab-separated file

### ISSUE THREAD

**Issue by xmao** [BurntSushi/xsv#58]
csvkit uses -t to specify tab as separator in file, instead of using -d "\t". It's really sweet shortcut.

**Comment by BurntSushi** [comment]
Alternatively, name your files `tsv` and xsv will do the right thing.

Otherwise, I think this is a dupe of #44.

**Comment by dnrce** [comment]
I think this is distinct functionality. It's not changing the default (#44), it's simply providing a shorthand for a one-time override. (Though admittedly #44 probably serves my own use case better.)
