### ISSUE TITLE
Do `xsv stats` and `xsv slice` respect the `--no-headers` option?

### ISSUE THREAD

**Issue by ldcasillas-progreso** [BurntSushi/xsv#6]
The help message printed by `xsv stats --help` mentions the `--no-headers` option:

        -n, --no-headers       When set, the first row will NOT be interpreted
                               as column names. i.e., They will be included
                               in statistics.

And yet I'm seeing the tool use the first column as the header in cases where I specify `--no-headers`:

    % head -n 1 2015-3-18_CA_5E63F293-8C7A-4737-A6CE-9E53DFB7DAF7.txt
    209,0000000

    % xsv stats --no-headers 2015-3-18_CA_5E63F293-8C7A-4737-A6CE-9E53DFB7DAF7.txt
    field,type,min,max,min_length,max_length,mean,stddev
    209,Integer,209,951,3,3,650.419291,216.581229
    0000000,Integer,0,9999999,7,7,5714603.611216,2326579.121568

    % xsv slice --no-headers -i 0 2015-3-18_CA_5E63F293-8C7A-4737-A6CE-9E53DFB7DAF7.txt
    209,0000000

Contrast with `xsv frequency`, which behaves as I expect:

    % xsv frequency --no-headers 2015-3-18_CA_5E63F293-8C7A-4737-A6CE-9E53DFB7DAF7.txt
    field,value,count
    1,310,1562992
    1,714,1406572
    1,916,1322587
    1,818,1291127
    1,760,1285504
    1,408,1185066
    1,805,1120246
    1,619,1113284
    1,510,1104539
    1,415,1100438
    2,0000000,22
    2,9999999,20
   [...]

**Comment by BurntSushi** [comment]
Hmm. I think both are behaving as I would expect. For `xsv slice`:

```
[andrew@Liger xsv] cat test.csv 
a,b,c
d,e,f
g,h,i
[andrew@Liger xsv] xsv slice -i0 test.csv 
a,b,c
d,e,f
[andrew@Liger xsv] xsv slice -i0 --no-headers test.csv 
a,b,c
[andrew@Liger xsv] xsv slice -i1 --no-headers test.csv 
d,e,f
```

In the first command, the slice returned is the first logical record and the headers. In the second and third commands, the first and second logical records are returned when the header row is included.

And for `xsv stats`:

```
[andrew@Liger xsv] xsv stats test.csv | xsv table
field  type     min  max  min_length  max_length  mean  stddev
a      Unicode  d    g    1           1                 
b      Unicode  e    h    1           1                 
c      Unicode  f    i    1           1                 
[andrew@Liger xsv] xsv stats --no-headers test.csv | xsv table
field  type     min  max  min_length  max_length  mean  stddev
a      Unicode  a    g    1           1                 
b      Unicode  b    h    1           1                 
c      Unicode  c    i    1           1 
```

Note that both invocations use the first row for the field names, but the actual stats gathered do not include the headers in the first command but *do* include the headers in the second command.

Perhaps an argument could be made that the field names should actually be field numbers when `--no-headers` is passed. But I think the semantics of the command are otherwise correct.

**Comment by ldcasillas-progreso** [comment]
> Perhaps an argument could be made that the field names should actually be field numbers when `--no-headers` is passed.

Taking as a given that the semantics is right, I would argue that:

1. At the very least all the subcommands should behave uniformly.  My examples show that `xsv stats` and `xsv frequency` behave differently.
2. Using the first row's values as column labels is going to confuse people, even if the semantics of the commands are otherwise right.  At the very least, people are going to hesitate whether `--no-headers` is working right.  Worst case scenario, somebody misinterprets a value-used-as-label as actual data.
3. I have three CSV files with the same logical fields and no headers; when I run stats on them I get different column names for the three files, which does not lend itself to, e.g., joining the `xsv stats` results from the three files.

**Comment by BurntSushi** [comment]
Agreed. :-)

**Comment by BurntSushi** [comment]
All set. I uploaded this in a new `0.8.41` release.
