### ISSUE TITLE
Feature request: import table from Excel (xslx/xls)

### ISSUE THREAD

**Issue by xmao** [BurntSushi/xsv#60]
I am a heavy csvkit user, and gradually transit to xsv now, only one exception in2csv that often makes me come back to csvkit.  A subcommand like, _import_, is very nice to import csv from Excel (xlsx or xls).

**Comment by BurntSushi** [comment]
Convert the xls file to csv first. xsv is unlikely to ever gain support for reading xls directly unless there is a pure Rust library that provides it (I certainly won't be building that library).

**Comment by xmao** [comment]
https://github.com/tafia/calamine is pure rust, looking promising.

**Comment by xmao** [comment]
https://github.com/evanmiller/rust-xls is a wrapper for libxls (C library)
