### ISSUE TITLE
Feature request: Filling in blanks

### ISSUE THREAD

**Issue by icefoxen** [BurntSushi/xsv#68]
Basically, I want to to be able to run `xsv impute` and have it replace blank values (or values with an out-of-bounds marker you can specify on the command line, such as "NA").  Obvious choices to fill in with would be a fixed value specified on the command line, or the same value as the previous cell in a row or column.

Value: It's hard to do this using sed or such, when a "blank value" could be the strings `,$` `,""$` `,,` `,"",` and so on.

Not sure how far one wants to go with this, since it'd be easy to feature creep "well why don't we add the option to fill in blanks with an average" "well why don't we add interpolation" "well why don't we let you put in an arbitrary equation" and so on.  Which is obviously not something xsv should care about.

**Comment by icefoxen** [comment]
Derp, this is intimately related to issue #38

**Comment by BurntSushi** [comment]
@icefoxen From my read of your issue, it actually seems like this is a dupe of #38. Is there something important that isn't captured by #38?

**Comment by icefoxen** [comment]
A little, but it's better carried on in #38 so that's what I'll do.
