### ISSUE TITLE
Could not convert '##' to a single ASCII character

### ISSUE THREAD

**Issue by kute** [BurntSushi/xsv#69]
The case is when i use `xsv count myfile.csv -d "##"` and how to use mutil char for delimiter ?

```
if s.len() != 1 {
                    let msg = format!("Could not convert '{}' to a single \
                                       ASCII character.", s);
                    return Err(d.error(&*msg));
}
```
I'm not sure that rewriting this could be worked and do not know why it can not be supported by `mutil char`.

**Comment by BurntSushi** [comment]
All delimiters must be a single byte. There's no support for multi byte delimiters.

**Comment by kute** [comment]
Of course usually it is. And `pandas.read_csv` is supported for multi byte delimiters.

**Comment by BurntSushi** [comment]
It's worth noting this part of the [Pandas `read_csv` documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html):

```
Delimiter to use. If sep is None, will try to automatically determine this. Separators longer than 1 character and different from '\s+' will be interpreted as regular expressions, will force use of the python parsing engine and will ignore quotes in the data. Regex example: '\r\t'
```

So if you're using this in Pandas, you're likely paying for it with slower parsing.

**Comment by kute** [comment]
Ok, i get it, thank you very much.
