### ISSUE TITLE
Friendlier help facility and unrecognized command errors

### ISSUE THREAD

**Issue by ldcasillas-progreso** [BurntSushi/xsv#7]
When I issue the command `xsv help` , this happens:

    % xsv help
    Could not match 'help' with any of the allowed variants: ["Cat", "Count", "FixLengths", "Flatten", "Fmt", "Frequency", "Headers", "Index", "Join", "Sample", "Search", "Select", "Slice", "Sort", "Split", "Stats", "Table"]

Because xsv is structured around the `xsv <command> [<args> ...]` paradigm, I find myself running into this all the time, and I can't imagine I'm the only one who will. 

I'm guessing it's low effort and high value to:

1. Add an actual `xsv help` subcommand
2. Dispatch `xsv help <command>` to the same code as `xsv <command> --help` (when `<command>` exists)
3. Dispatch to the same code as `xsv --help` when the user issues `xsv help` or `xsv help <command>` for a non-existent command.

**Comment by BurntSushi** [comment]
Spot on! Fixed. I'm uploading a `0.8.40` release now.

**Comment by ldcasillas-progreso** [comment]
Thanks!
