### ISSUE TITLE
Search/inverted search get confused by this line

### ISSUE THREAD

**Issue by jonasbb** [BurntSushi/xsv#70]
I have a line of valid CSV data, which is selected regardless of which columns I select, whether I used inverted matching, or which search term I use.

I installed version 0.11.0 with cargo install.

Line of CSV data (`y.csv`):
```
1970-01-01 00:00:51.000000,1970-01-01 00:31:34.000000,222.91.247.73,172.31.13.174,17,"{0,0,0,10}"
```

I would expect that not all of these invocations will print the line:
``` bash
xsv search -v 999999999999999 /tmp/y.csv
xsv search 999999999999999 /tmp/y.csv  # prints the line even though there is no match
xsv search 1970 /tmp/y.csv
xsv search -v 1970 /tmp/y.csv # prints the line even though there is a match and inverted filtering is on
```

**Comment by BurntSushi** [comment]
`xsv` interprets the first line of CSV data as headers, and so the header row is usually printed unconditionally. If you don't want that behavior, then disable it with the `-n/--no-headers` flag.

**Comment by jonasbb** [comment]
Thank you for the help. Sorry for the trouble, I should have checked the documentation before.
