### ISSUE TITLE
[feat] search does not work across multiple columns

### ISSUE THREAD

**Issue by eddy-geek** [BurntSushi/xsv#71]
Current search behaviour is confusing, you can select multiple columns with `-e` but the pattern is applied to each column separately. Drawbacks:

* This is a bit confusing as my mental model from reading the doc was some kind of `xsv select <columns> | grep <pattern>`
* It means there is no way to say column1=pattern1 **AND** column2=pattern2

Example to clarify:
```bash
> echo $'h1,h2\nv1,v2\nv3,v4' > tmp.csv
> xsv search -s h1,h2 v1 tmp  # OK
h1,h2
v1,v2
> xsv search -s h1,h2 v2 tmp  #OK
h1,h2
v1,v2
> xsv search -s h1,h2 v1,v2 tmp  #KO
h1,h2
> xsv search -s h1,h2 'v1.*v2' tmp  #KO
h1,h2
```

**Comment by BurntSushi** [comment]
@eddy-geek This is intended behavior. Could you please help me understand how I can change the documentation of `xsv search -h` to make this clearer?

If you want to search the entire row, then just use grep, or even better, [ripgrep](https://github.com/BurntSushi/ripgrep). :-)

**Comment by BurntSushi** [comment]
> It means there is no way to say column1=pattern1 AND column2=pattern2

Uh, of course there is! :-)

```
[andrew@Serval tmp] cat tmp.csv 
h1,h2
v1,v2
v1,v4
[andrew@Serval tmp] xsv search -s h1,h2 v1 tmp.csv | xsv search -s h1,h2 v2 
h1,h2
v1,v2
```

**Comment by eddy-geek** [comment]
Ah! the pipe, of course :)... not the most performant if you don't think about the order, but does the job.

For the doc, it is quite clear, my bad, I did not read the intro, only the `-s` section which is a bit bare:
    -s, --select <arg>     Select the columns to search. See 'xsv select -h'
                           for the full syntax.

I still don't see many uses for the current default behaviour, but if it's intended OK :)

**Comment by BurntSushi** [comment]
> I still don't see many uses for the current default behaviour

The use case is, "I want to search for a particular value in a particular field." The tutorial in the README contains such a use case. It's important for this feature to be built into `xsv` because it enables matching on the *decoded* field data rather than the *encoded* field data, which is what you'd get if you use grep.
