### ISSUE TITLE
Add the ability to ingest gzip'd csv

### ISSUE THREAD

**Issue by valarauca** [BurntSushi/xsv#73]
Google bigquery API's commonly will dump `*.csv.gz` files on you. Which are normally single csv file, gzipped. I've been using a custom [`libflate`](https://crates.io/crates/libflate) for the task of unzipping these csv files, but then just dumping that output directly into `xsv cat rows`. 

Would you mind adding a `--gzip` switch to mark the input is a `gzip.csv` file?

**Comment by BurntSushi** [comment]
Is there a reason why you can't run `gzip -d` over the file first?

Folks want this functionality added to ripgrep as well, but I'm not sure I want the maintenance burden of using a young gzip re-implementation. (But I also don't want the maintenance burden of taking on a C dep.)

**Comment by valarauca** [comment]
Doing that over 40+ files isn't fun. Also writing a lot of custom bash or python scripts to handle the _fun_ of files without extensions and terminal wild cards isn't great.

**Comment by nbigaouette** [comment]
I'd be interested too with this. I have a 2.6 GB `.gz` file that, when extracted, is around 15 GB.

Anything that can be done to prevent me from working on the whole extracted datafile (disk wise, memory wise) is a win.

For now, I use `zcat` instead of `gzip -d` for basic access to the file:
```
$ zcat data.gz | xsv headers
```

**Comment by dubyte** [comment]
I will use zcat I was looking for this because I have a 20gb gzip that unconpressed is 100gb :(
