### ISSUE TITLE
Color xsv table output

### ISSUE THREAD

**Issue by beojan** [BurntSushi/xsv#75]
It would be useful if the output of `xsv table` could be colored, to clearly differentiate between the headers and data.

**Comment by tseemann** [comment]
+1

**Comment by BurntSushi** [comment]
@tseemann +1 comments are rude and only serve to create noise. Please don't do it again on any of my issue trackers.

**Comment by tseemann** [comment]
I think you meant to write "*I think* +1 comments are rude ..."

I will honour your request and only annotate the original comment with 👍 

I have deleted my original noisy comment.

**Comment by beojan** [comment]
The (one) problem with +1 comments is that they trigger a notification
email.

**Comment by tseemann** [comment]
I strongly suspect the prolific @BurntSushi has disabled email notifications, but yes, it will still add an in-browser notification.  

The counter argument is that 👍 do *not* triggger a notification, so you never realise the +1s are piling up.  I've seen this happen before.

**Comment by BurntSushi** [comment]
> I strongly suspect the prolific @BurntSushi has disabled email notifications

No, I haven't.

**Comment by tseemann** [comment]
I stand corrected. Do you filter them to mail folders / labels though?

**Comment by BurntSushi** [comment]
@tseemann I've hidden all comments related to +1'ing a post and the subsequent inquiry into my email habits. I'm hoping this will be the last word on the matter.

**Comment by beojan** [comment]
That doesn't seem to have worked.

You could just delete the issue. I use VisiData for taking a quick look at a CSV now, so this request doesn't matter to me anymore.
