### ISSUE TITLE
What is the recommended approach to align csv files?

### ISSUE THREAD

**Issue by chrisbra** [BurntSushi/xsv#8]
Hi, I am the author of a csv-plugin for vim and consider using xsv if available to align csv files nicely into tables. At first I thought, xsv table would be all I need, however it seems, that xsv table just makes the fields larger than needed and does not consider header lines. So my question is, is there a recommended way to align csv files so that each field is as large as needed but not larger?

**Comment by BurntSushi** [comment]
Can you give me an example where `xsv table` doesn't work? It should align everything, including header fields. It might have an extra space or two to make the output look nice, but you should be able to twiddle that. (See `xsv table --help`.)

**Comment by chrisbra** [comment]
Oh, I think, I just missed the -d option. 
I'll will test a bit more and see if this works out for me
