### ISSUE TITLE
Example for input

### ISSUE THREAD

**Issue by andrewnguyen42** [BurntSushi/xsv#81]
I can't find any examples of how this is used, and this repo is the only source documentation

**Comment by BurntSushi** [comment]
@andrewnguyen42 Could you please say more about what you don't understand in `xsv input --help`?

**Comment by andrewnguyen42** [comment]
it's not immediately clear to me what the quote character or escape characters are used for. I get some weird behavior when interpreting lines with quotes, so I was looking to whether this command could be useful for that

**Comment by BurntSushi** [comment]
Consider the field data `Bret "The Hit Man" Hart`. How do you encode that in CSV data? You need to escape the quotes some how. The standard would be to encode by doubling the quotes, for example, `"Bret ""The Hit Man"" Hart"`, but there's plenty of data that uses a standard escape instead: `"Bret \"The Hit Man\" Hart"`. The quote and escape flags allow you to pick which characters you want to use.

**Comment by BurntSushi** [comment]
> I get some weird behavior when interpreting lines with quotes

The only way I can help is if you provide an example. What command did you run? What data did you run it on? What did you expect to happen?

And more generally: *What problem are you trying to solve?*

**Comment by andrewnguyen42** [comment]
Specifically, the below record is interpreted as having 3 fields instead of 4. I suspect it's because of some weird quoting rules

field1|field2|field3
a|"weird quote'| c

**Comment by BurntSushi** [comment]
Could you tell me what the fields are supposed to be? It looks like 3 fields to me.

**Comment by andrewnguyen42** [comment]
Apologies, that should have said '2 fields instead of 3' the specific command is

$ xsv stats --delimiter "|" test.csv
CSV error: record 1 (line: 2, byte: 21): found record with 2 fields, but the previous record has 3 fields

**Comment by BurntSushi** [comment]
Yes, your CSV data is busted. I'm not sure what you expect to happen. If your quote is `"`, then the second `|` in `a|"weird quote'| c` is treated as a normal `|` since it is inside quotes.

**Comment by andrewnguyen42** [comment]
Indeed. Is there any way to ignore quotes altogether? That's kind of where I was hoping the input command would save me

**Comment by BurntSushi** [comment]
No, you can't just ignore quotes. You can specify a quote character that never occurs though:

```
$ xsv input --quote \0 /tmp/scratch.csv | xsv stats
```

**Comment by andrewnguyen42** [comment]
Hmmm looks like that ends up putting quotes at the beginning and end of the lines too

field1|field2|field3
"a|""weird quote'| c"

I guess I'll have to go with something kind of gross like 
`sed 's/\"//g;s/\'//g' test.csv | xsv stats`

**Comment by za3k** [comment]
Actually, sorry to bump this, but it would be very helpful to add your specific `--escape '\'` example to this command as an example (maybe even a troubleshooting section of the readme.

I think anything you need to "get started" deserves a bump

**Comment by bestouff** [comment]
Also bumping. I need to remove a column from a csv file using `;` as the separator, but I have a hard time seeing how it works:
```
$ xsv -d ';' select '!3' c1.csv 
Unknown flag: '-d'

Usage:
    xsv <command> [<args>...]
    xsv [options]

$ xsv --delimiter ';' select '!3' c1.csv 
Unknown flag: '--delimiter'

Usage:
    xsv <command> [<args>...]
    xsv [options]

$ xsv input --delimiter ';' select '!3' c1.csv 
Invalid arguments.

Usage:
    xsv input [options] [<input>]

$ xsv input --delimiter ';' c1.csv select '!3'
Invalid arguments.

Usage:
    xsv input [options] [<input>]

$ xsv select '!3' input --delimiter ';' c1.csv 
Invalid arguments.

Usage:
    xsv select [options] [--] <selection> [<input>]
    xsv select --help
```

There's probably a solution somewhere I'll find by reading the source code, but it's not clear at all from the `--help` message. Also the error messages `Invalid arguments` aren't that helpful.  
And also I now realize this message is a bit rough, so thanks a lot for the time you're sinking into `xsv`; it's such a nice tool.

**Comment by BurntSushi** [comment]
Also, the error messages include "usage" information. It doesn't just say "invalid arguments." The usage tells you what's valid.

**Comment by bestouff** [comment]
```
$ xsv -d ';' select '!3' connectivity1.csv 
Unknown flag: '-d'

Usage:
    xsv <command> [<args>...]
    xsv [options]
```
I agree with you, the error messages are more helpful than what I said, sorry for that.

**Comment by bestouff** [comment]
For now the only solution that works for me is `xsv input -d ';' connectivity1.csv | xsv select '!3'` and I understand that, I simply didn't understood from the help that I can run only 1 command at a time.  
Thinking about it, it's probably just me being dense...

**Comment by nk2343** [comment]
Hi, I am running command xsv join --left var1 file1.csv var2 file2.csv > file3.csv and got the following error: line3 : found records with 2 fields, but the previous record has 1 fields. I checked file1 and found that line 3 has a ",". Do you know how to solve this kind of problem? Thank you!

**Comment by BurntSushi** [comment]
I'm not sure why you're posting in an old issue. And your question doesn't have enough details to be answered. Please open a new issue. Include the actual command you're running, the input, the actual output and the desired or expected output.

**Comment by Ayken4206** [comment]
Hi BurntSushi, I just wanted to thank you for your great contribution. I used your xsv tool from PowerShell and managed to filter a csv file with 800million lines and 30 columns (135GB size). It took me around 4 mintutes.

develop the script and use PS2EXE ->> create and exe file
Run the exe file
extract ZIP file (13GB) with 7ZIP and get csv file (135GB)
apply select and search filters using xsv (in 4 steps)
get the final.csv (426MB) size

All is completed in 4 minutes.

Thanks.
