### ISSUE TITLE
Please make xsv table command optionally output the delimiter

### ISSUE THREAD

**Issue by chrisbra** [BurntSushi/xsv#9]
As per the subject. I'd like to keep the delimiter if possible

**Comment by chrisbra** [comment]
e.g. for this file:
 First,Second,Third
  10,5,2
  5,2,10
  2,10,5
  10,5,2

output it like this:
 First, Second, Third
      10,      5,     2
       5,      2,    10
       2,     10,     5
      10,      5,     2

(and optionally aligning colums (without the delimiter) like this (for leftaligning):
  First  ,Second  ,Third
  10     ,5       ,2
  5      ,2       ,10
  2      ,10      ,5
  10     ,5       ,2

**Comment by BurntSushi** [comment]
That doesn't really make sense to me. What is your use case? `xsv table` is for making CSV files human readable on the console. Keeping the delimiters in the output conflicts with this goal. `xsv table`'s purpose is to replace delimiters with the right number of spaces.

*Aside* from that, I'm especially unlikely to implement this. The [existing command](https://github.com/BurntSushi/xsv/blob/master/src/cmd/table.rs#L57-L59) is especially simple because it relies on an implementation of elastic tabstops.

**Comment by chrisbra** [comment]
I am hoping to use xsv if available to arrange csv files within vim. I have a vim [CSV plugin](https://github.com/chrisbra/csv.vim/), [screencast](http://www.256bit.org/~chrisbra/csv.gif) (Look for the :ArrangeCol command) That allows to align csv files and instead of calculating the correct width and aligning it manually, I'd like to use xsv if possible. Because this is faster (which makes a difference for bigger csv files). But this makes only sense, if I can keep the delimiter, and second (optionally) be able to specify how to align certain columns.

**Comment by BurntSushi** [comment]
That's an impressive plugin!

Honestly, I'm not sure that the command you're after is a good fit for `xsv`. It seems rather specialized and of limited practical use. If you wanted to write a new command called `align` as part of `xsv` and it was simple enough, I'd probably be willing to maintain it. But I think that's about the best I can do.

If I saw an easy way to do this on top of `xsv table`, then I might do it. But unfortunately, most of the complexity is buried in elastic tabstops which has no knowledge of delimiter separated values.

**Comment by chrisbra** [comment]
Okay, thanks. I'll check, if csvkit can help me.

**Comment by BurntSushi** [comment]
OK, good luck! As far as I know, `csvkit`'s closest thing is `csvlook`, but it has lots of formatting that probably won't work for you.

You might also consider investigation the `column` command that is part of `util-linux`.
