### ISSUE TITLE
How to select columns which have dash in name

### ISSUE THREAD

**Issue by aubergene** [BurntSushi/xsv#91]
I have a CSV which unfortunately has dashes in the column names and I can't find a way of selecting them using XSV.

test.csv
```csv
name with space,name - with dash
1,2
```

```
xsv select 'with - dash' test.csv
Selector name 'with ' does not exist as a named header in the given CSV data.
```

**Comment by aubergene** [comment]
Wait, I worked it out :)

It looks like single quotes to escape the selector and then double quotes around each column name. I hope this helps someone else

```
xsv select '"dash - 2","dash - 1"' test.csv
```

**Comment by BurntSushi** [comment]
Glad you figured it out! There are other examples in the output of `xsv select --help`:

```
$ xsv select --help
Select columns from CSV data efficiently.

This command lets you manipulate the columns in CSV data. You can re-order
them, duplicate them or drop them. Columns can be referenced by index or by
name if there is a header row (duplicate column names can be disambiguated with
more indexing). Finally, column ranges can be specified.

  Select the first and fourth columns:
  $ xsv select 1,4

  Select the first 4 columns (by index and by name):
  $ xsv select 1-4
  $ xsv select Header1-Header4

  Ignore the first 2 columns (by range and by omission):
  $ xsv select 3-
  $ xsv select '!1-2'

  Select the third column named 'Foo':
  $ xsv select 'Foo[2]'

  Re-order and duplicate columns arbitrarily:
  $ xsv select 3-1,Header3-Header1,Header1,Foo[2],Header1

  Quote column names that conflict with selector syntax:
  $ xsv select '"Date - Opening","Date - Actual Closing"'
```

**Comment by poolfactory** [comment]
Hello, I have a similar problem on Windows Command Line. This is what I get.
`xsv select '"Artikelnummer 13-st."'
Selector name ''Artikelnummer 13' does not exist as a named header in the given CSV data.`
Could you please gibe me some advice. Thanks.

**Comment by BurntSushi** [comment]
@poolfactory A similar question came up on another tool I maintain: https://github.com/BurntSushi/ripgrep/discussions/1743#discussioncomment-136868

Good luck. I don't use Windows and PowerShell's quoting problems are pretty nutty.
