### ISSUE TITLE
Overwriting file erases the content

### ISSUE THREAD

**Issue by ishitatsuyuki** [BurntSushi/xsv#92]
```
 ishitatsuyuki@X1Yoga  /tmp  xsv sort test.csv -o 2.csv                 
 ishitatsuyuki@X1Yoga  /tmp  cat 2.csv 
a,b,c,d,e
g,h,i,j,k
 ishitatsuyuki@X1Yoga  /tmp  xsv sort test.csv -o test.csv
 ✘ ishitatsuyuki@X1Yoga  /tmp  cat test.csv 
a,b,c,d,e
g,h,i,j,k
 ishitatsuyuki@X1Yoga  /tmp  xsv sort test.csv -o test.csv
 ishitatsuyuki@X1Yoga  /tmp  cat test.csv
 ishitatsuyuki@X1Yoga  /tmp  
```

`**BOOM**`

I have confirmed that UNIX commands (I used `iconv`) without an `-i` switch (and `-o` instead) should properly process if the same file is passed.

I'm using 0.12.1 and I haven't updated yet. I see a refactor in commit log, but I'm not sure if this is fixed in the process.

**Comment by BurntSushi** [comment]
Ummm. You are reading and writing to the same file. Bad things will happen in the same way that running `xsv sort foo.csv > foo.csv` will cause bad things to happen.

I'm not inclined to fix this since this is pretty standard unix behavior, but I could be convinced to add an error message.

**Comment by ishitatsuyuki** [comment]
Output redirect is well-known to wipe the file; however, `-o` is well known as the workaround.

Other than `iconv`, `sort` also does: https://stackoverflow.com/questions/29244351/how-to-sort-a-file-in-place

**Comment by BurntSushi** [comment]
Fair enough. Seems like a good idea then.

**Comment by cup** [comment]
https://github.com/BurntSushi/xsv/issues/200
