### ISSUE TITLE
- normalize the amount of spaces for numerical fields

### ISSUE THREAD

**Issue by posix4e** [BurntSushi/xsv#93]
Honestly i'd be happy if this existed even if it also trimmed strings to start.

**Comment by BurntSushi** [comment]
I don't understand this feature request. Please tell me what have you tried? What did you expect to happen? Can you provide sample input, actual output and expected output? What higher level problem are you trying to solve?

**Comment by posix4e** [comment]
I've got a file like


String, 1.010101, 0.23123,.... (some number of times)

I want to deser this without calling trim and parse
