### ISSUE TITLE
Bug in xsv table

### ISSUE THREAD

**Issue by radostyle** [BurntSushi/xsv#95]
There is a bug in table that after a certain point the results get thrown off.

Although all the lines are the same
At line 141 of this file it looks like this

![image](https://user-images.githubusercontent.com/151909/29835802-b699fb9e-8cb8-11e7-8a3b-1619d84dc6c3.png)

**Comment by radostyle** [comment]
Uploaded test file

[bug2.txt](https://github.com/BurntSushi/xsv/files/1261184/bug2.txt)

xsv table bug2.txt

**Comment by radostyle** [comment]
xsv --version
0.12.2

on OSX using homebrew.

**Comment by nhoffman** [comment]
I'd like to +1 this bug report with an additional test case (attached). Also using 0.12.2 installed via homebrew.

[table.txt](https://github.com/BurntSushi/xsv/files/1469063/table.txt)
<img width="1159" alt="screen shot 2017-11-13 at 3 54 23 pm" src="https://user-images.githubusercontent.com/440002/32755646-258cbbfa-c88b-11e7-820b-08073c9f6f8e.png">

**Comment by Yomguithereal** [comment]
Isn't this happening because the library only reads a fixed amount of rows into a buffer not to overload memory and then when you stumble upon a larger cell value columns need to be resized? I usually use the `fixlengths` command before piping into table to handle those cases.

**Comment by BurntSushi** [comment]
Yes, if you have records with different row sizes, then `xsv table` won't align them correctly.
